/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole;

import Business.Business;
import javax.swing.JPanel;
import university.CourseSchedule.CourseSchedule;
import university.Department.Department;
import Business.Profiles.StudentProfile;


/**
 *
 * @author Lanre
 */
public class StudentRegistrationJPanel extends javax.swing.JPanel {
    private Business business;              
    private JPanel CardSequencePanel;       
    private CourseSchedule currentSchedule;
    
    
    /**
     * Creates new form StudentRegistrationJPanel
     */
    public StudentRegistrationJPanel(Business business, JPanel CardSequencePanel) {
        initComponents();
        this.business = business;                 // store reference to business
        this.CardSequencePanel = CardSequencePanel; // store card panel for navigation
        
        cmbStudent.setPreferredSize(new java.awt.Dimension(120, 25));
        cmbDepartment.setPreferredSize(new java.awt.Dimension(120, 25));
        btnLoad.setPreferredSize(new java.awt.Dimension(120, 30));

        populateDepartments(); // load departments into dropdown
        populateStudents();    // load students into dropdown
  
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudent = new javax.swing.JLabel();
        cmbStudent = new javax.swing.JComboBox<>();
        lblDepartment = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();
        lblSemester = new javax.swing.JLabel();
        txtSemester = new javax.swing.JTextField();
        btnLoad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOfferings = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudentSchedule = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnEnroll = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();

        lblStudent.setText("Student");

        cmbStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStudentActionPerformed(evt);
            }
        });

        lblDepartment.setText("Department");

        lblSemester.setText("Semester");

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        tblOfferings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Faculty", "Credit", "Seat Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOfferings);

        tblStudentSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Faculty", "Credit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblStudentSchedule);

        btnBack.setText("<<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnDrop.setText("Drop");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStudent)
                            .addComponent(lblDepartment)
                            .addComponent(lblSemester))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbStudent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(236, 236, 236))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEnroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDrop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudent)
                    .addComponent(cmbStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLoad)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(27, 27, 27)
                        .addComponent(btnEnroll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDrop)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        // 1) Read selected department from dropdown
        //System.out.println("LOAD CLICKED");
        Department d = (Department) cmbDepartment.getSelectedItem();
        if (d == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a department.");
            return;
        }

        // 2) Read semester from text field
        String semester = txtSemester.getText().trim();
        if (semester.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter a semester (e.g., Fall 2025).");
            return;
        }

        // 3) Get the course schedule for that semester (create if missing)
        currentSchedule = d.getCourseSchedule(semester);
        if (currentSchedule == null) {
            // create an empty schedule if it doesn't exist yet
            currentSchedule = d.newCourseSchedule(semester);
        }

        //System.out.println("Dept=" + d + ", semester=" + semester);
        
        //System.out.println("Schedule is null? " + (currentSchedule == null));
        //System.out.println("Offerings count = " + currentSchedule.getSchedule().size());
        
        // 4) Populate the offerings table
        populateOfferingsTable(currentSchedule);

        university.CourseSchedule.CourseLoad cl = getSelectedStudentCourseLoad(semester);
        if (cl != null) {
            populateStudentScheduleTable(cl);
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void cmbStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStudentActionPerformed
        // TODO add your handling code here:
        // Refresh student schedule only if semester is set and schedule is loaded
        String semester = txtSemester.getText().trim();
        if (semester.isEmpty()) {
            return;
        }
        if (currentSchedule == null) {
            return;
        }

        university.CourseSchedule.CourseLoad cl = getSelectedStudentCourseLoad(semester);
        if (cl != null) {
            populateStudentScheduleTable(cl);
        }
    }//GEN-LAST:event_cmbStudentActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        // TODO add your handling code here:
        // 1) Ensure a course is selected in offerings table
        int selectedRow = tblOfferings.getSelectedRow();
        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a course to enroll.");
            return;
        }

        // 2) Get semester
        String semester = txtSemester.getText().trim();
        if (semester.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter semester first.");
            return;
        }

        // 3) Get selected course number from table
        String courseNumber = tblOfferings.getValueAt(selectedRow, 0).toString();

        // 4) Get selected student CourseLoad
        university.CourseSchedule.CourseLoad cl = getSelectedStudentCourseLoad(semester);
        if (cl == null) {
            return;
        }

        // 5) Prevent duplicate enrollment
        if (cl.isAlreadyEnrolled(courseNumber)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Student already enrolled.");
            return;
        }

        // 6) Get CourseOffer from schedule
        university.CourseSchedule.CourseOffer co
                = currentSchedule.getCourseOfferByNumber(courseNumber);

        // 7) Attempt seat assignment
        university.CourseSchedule.SeatAssignment sa = cl.newSeatAssignment(co);

        if (sa == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Course is full.");
            return;
        }

        // 8) Refresh both tables
        populateOfferingsTable(currentSchedule);
        populateStudentScheduleTable(cl);
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        // TODO add your handling code here:
        // 1) Ensure a course is selected in the student schedule table
        int selectedRow = tblStudentSchedule.getSelectedRow();
        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select an enrolled course to drop.");
            return;
        }

        // 2) Get semester
        String semester = txtSemester.getText().trim();
        if (semester.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter semester first.");
            return;
        }

        // 3) Get course number from selected row
        String courseNumber = tblStudentSchedule.getValueAt(selectedRow, 0).toString();

        // 4) Get the student's CourseLoad for the semester
        university.CourseSchedule.CourseLoad cl = getSelectedStudentCourseLoad(semester);
        if (cl == null) {
            return;
        }

        // 5) Drop course (frees seat + removes seatassignment)
        cl.dropCourse(courseNumber);

        // 6) Refresh both tables
        populateOfferingsTable(currentSchedule);
        populateStudentScheduleTable(cl);
    }//GEN-LAST:event_btnDropActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Go back to previous panel in CardLayout
        CardSequencePanel.remove(this);
        java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnLoad;
    private javax.swing.JComboBox<Department> cmbDepartment;
    private javax.swing.JComboBox<StudentProfile> cmbStudent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JTable tblOfferings;
    private javax.swing.JTable tblStudentSchedule;
    private javax.swing.JTextField txtSemester;
    // End of variables declaration//GEN-END:variables

    private void populateDepartments() {
        cmbDepartment.removeAllItems();
        for (Department d : business.getDepartments()) {
            cmbDepartment.addItem(d);
        }
    }
    
    private void populateStudents() {
        cmbStudent.removeAllItems();
        for (StudentProfile sp : business.getStudentDirectory().getStudentList()) {
            cmbStudent.addItem(sp);
        }
    }

    private void populateOfferingsTable(CourseSchedule cs) {
        // clear and refill offerings table from schedule
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) tblOfferings.getModel();
        model.setRowCount(0);

        for (university.CourseSchedule.CourseOffer co : cs.getSchedule()) {
            // key used for enroll/drop lookups
            String courseId = co.getCourseNumber();

            // display-friendly course name
            String courseName = co.getSubjectCourse().getName();

            // show instructor if assigned, otherwise TBA
            String faculty = (co.getFacultyProfile() != null)
                    ? co.getFacultyProfile().getPerson().getPersonId()
                    : "TBA";

            // credits shown in table
            int credits = co.getCreditHours();

            
            String seats = (co.getEmptySeat() != null) ? "Yes" : "Full";

            model.addRow(new Object[]{courseId, courseName, faculty, credits, seats});
        }
    }

    private void populateStudentScheduleTable(university.CourseSchedule.CourseLoad cl) {
        // Clear and refill student schedule table from the CourseLoad
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) tblStudentSchedule.getModel();
        model.setRowCount(0);

        for (university.CourseSchedule.SeatAssignment sa : cl.getSeatAssignments()) {

            university.CourseSchedule.CourseOffer co = sa.getCourseOffer();

            String courseId = co.getCourseNumber();                 // used for drop
            String courseName = co.getSubjectCourse().getName();    // display name

            String faculty = (co.getFacultyProfile() != null)
                    ? co.getFacultyProfile().getPerson().getPersonId()
                    : "TBA";

            int credits = sa.getCreditHours();                      // course credits

            model.addRow(new Object[]{courseId, courseName, faculty, credits});
        }
    }
    
    private university.CourseSchedule.CourseLoad getSelectedStudentCourseLoad(String semester) {
        // Get selected Business student profile
        StudentProfile sp = (StudentProfile) cmbStudent.getSelectedItem();
        if (sp == null) {
            return null;
        }

        // Bridge to university student profile (where transcript/courseload lives)
        university.Persona.StudentProfile usp = sp.getUniversityProfile();
        if (usp == null) {
            return null;
        }

        // Get or create courseload for this semester
        university.CourseSchedule.CourseLoad cl = usp.getCourseLoadBySemester(semester);
        if (cl == null) {
            cl = usp.newCourseLoad(semester);
        }

        return cl;
    }
}
