/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.RegistrarProfile;
import Business.UserAccounts.UserAccount;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class AdministerStudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    UserAccount selecteduseraccount;
    Business business;

    public AdministerStudentJPanel(UserAccount sua, Business bz, JPanel jp) {

        CardSequencePanel = jp;
        this.business = bz;
        selecteduseraccount= sua;
        initComponents();
        populatefields();
        setviewmode();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        pwPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        pwConfirmPassword = new javax.swing.JPasswordField();
        txtName = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        lblProfileType = new javax.swing.JLabel();
        txtCreated = new javax.swing.JTextField();
        txtNUID = new javax.swing.JTextField();
        lblCreated = new javax.swing.JLabel();
        lblNUID = new javax.swing.JLabel();
        cbxRole = new javax.swing.JComboBox<>();
        btnSavePw = new javax.swing.JButton();
        btnResetPw = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtOfficeHours = new javax.swing.JTextField();
        lblOfficeHours = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 430, 74, 23);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Manage User Account");
        add(lblTitle);
        lblTitle.setBounds(30, 20, 550, 28);
        add(txtUsername);
        txtUsername.setBounds(140, 140, 140, 30);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(520, 300, 72, 23);

        lblName.setText("Name");
        add(lblName);
        lblName.setBounds(90, 200, 50, 20);

        lblUsername.setText("Username");
        add(lblUsername);
        lblUsername.setBounds(70, 150, 70, 20);
        add(pwPassword);
        pwPassword.setBounds(300, 370, 140, 30);

        lblPassword.setText("Password");
        add(lblPassword);
        lblPassword.setBounds(230, 380, 70, 20);

        lblConfirmPassword.setText("Confirm Password ");
        add(lblConfirmPassword);
        lblConfirmPassword.setBounds(190, 430, 110, 20);
        add(pwConfirmPassword);
        pwConfirmPassword.setBounds(300, 420, 140, 30);
        add(txtName);
        txtName.setBounds(140, 190, 140, 30);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit);
        btnEdit.setBounds(210, 300, 72, 23);

        lblProfileType.setText("Profile Type");
        add(lblProfileType);
        lblProfileType.setBounds(60, 100, 80, 20);
        add(txtCreated);
        txtCreated.setBounds(140, 240, 140, 30);
        add(txtNUID);
        txtNUID.setBounds(450, 90, 140, 30);

        lblCreated.setText("Created Date");
        add(lblCreated);
        lblCreated.setBounds(60, 250, 80, 16);

        lblNUID.setText("NUID");
        add(lblNUID);
        lblNUID.setBounds(370, 100, 80, 16);

        cbxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Registrar", "Faculty", "Student" }));
        add(cbxRole);
        cbxRole.setBounds(140, 92, 140, 30);

        btnSavePw.setText("Save password");
        btnSavePw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePwActionPerformed(evt);
            }
        });
        add(btnSavePw);
        btnSavePw.setBounds(487, 420, 110, 23);

        btnResetPw.setText("Reset Password");
        btnResetPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPwActionPerformed(evt);
            }
        });
        add(btnResetPw);
        btnResetPw.setBounds(340, 300, 120, 23);
        add(txtEmail);
        txtEmail.setBounds(450, 140, 140, 30);
        add(txtPhone);
        txtPhone.setBounds(450, 190, 140, 30);

        lblEmail.setText("Email");
        add(lblEmail);
        lblEmail.setBounds(370, 150, 80, 16);

        lblPhone.setText("Phone");
        add(lblPhone);
        lblPhone.setBounds(370, 200, 80, 16);
        add(txtOfficeHours);
        txtOfficeHours.setBounds(450, 240, 140, 30);

        lblOfficeHours.setText("Office Hours");
        add(lblOfficeHours);
        lblOfficeHours.setBounds(370, 250, 80, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // I want to load a fresh ManageEmployeesJPanel so that the table refreshes
        CardSequencePanel.remove(this);
        
        ManageStudentsJPanel msp = new ManageStudentsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("Manage Students Panel", msp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        updateuserinfo();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // Turn fields to editable
        seteditmode();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPwActionPerformed
        // Reset password sequence. Turns on hidden fields, sets them to editable.
        resetpassword();
    }//GEN-LAST:event_btnResetPwActionPerformed

    private void btnSavePwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePwActionPerformed
        // save password sequence (extract passwords, validate, save)
        savepassword();
    }//GEN-LAST:event_btnSavePwActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnResetPw;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSavePw;
    private javax.swing.JComboBox<String> cbxRole;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblCreated;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNUID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOfficeHours;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblProfileType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwConfirmPassword;
    private javax.swing.JPasswordField pwPassword;
    private javax.swing.JTextField txtCreated;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNUID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOfficeHours;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void populatefields() {
        //Get the Person for the user account
        Person person = selecteduseraccount.getAssociatedPersonProfile().getPerson();
                
        //Populate common fields
        txtName.setText(person.getFullname());
        txtUsername.setText(selecteduseraccount.getUserLoginName());
        txtNUID.setText(person.getPersonId());
        txtCreated.setText(formatTimestamp(person.getCreatedtimestamp()));
        txtEmail.setText(selecteduseraccount.getAssociatedPersonProfile().getEmail());
        txtPhone.setText(selecteduseraccount.getAssociatedPersonProfile().getPhone());
        
        //hide password fields
        pwPassword.setVisible(false);
        pwConfirmPassword.setVisible(false);
        lblPassword.setVisible(false);
        lblConfirmPassword.setVisible(false);
        btnSavePw.setVisible(false);
        
        // Populate Student-specific field
        //RegistrarProfile rp = (RegistrarProfile) selecteduseraccount.getAssociatedPersonProfile();
        //txtOfficeHours.setText(rp.getOfficeHours() != null ? rp.getOfficeHours() : "");
    }
        
    private void setviewmode() {
        txtName.setEnabled(false);
        txtUsername.setEnabled(false);
        txtNUID.setEnabled(false);
        txtCreated.setEnabled(false);
        txtEmail.setEnabled(false);
        txtPhone.setEnabled(false);
       // txtOfficeHours.setEnabled(false);
    }

    private void updateuserinfo() {
        String name = txtName.getText().trim();
        String username = txtUsername.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();
     //   String officeHours = txtOfficeHours.getText().trim();

        // Validate required fields
        if (name.isBlank() || username.isBlank() || email.isBlank()) {
            JOptionPane.showMessageDialog(this, "Name, Email, and Username are required");
            return;
        }

        // Verify username is not taken
        UserAccount u = business.getUserAccountDirectory().findusername(username);
        if (u != null && u != selecteduseraccount) {
            JOptionPane.showMessageDialog(this, "Username is taken. Please select another username.");
            return;
        }

        // Verify email is not taken
        if (business.getUserAccountDirectory().isEmailTaken(email, selecteduseraccount)) {
            JOptionPane.showMessageDialog(this, "Email is already in use");
            return;
        }

        // Save common fields
        Person person = selecteduseraccount.getAssociatedPersonProfile().getPerson();
        person.setFullname(name);
        selecteduseraccount.setUsername(username);
        selecteduseraccount.getAssociatedPersonProfile().setEmail(email);
        selecteduseraccount.getAssociatedPersonProfile().setPhone(phone);

        // Save Student-specific field
     //   StudentProfile sp = (StudentProfile) selecteduseraccount.getAssociatedPersonProfile();
     //   sp.setOfficeHours(officeHours);

        // Update timestamp
        selecteduseraccount.updatelastupdate();

        // Navigate back to fresh ManageEmployeesJPanel
        JOptionPane.showMessageDialog(this, "Student account updated successfully");
        CardSequencePanel.remove(this);
        ManageStudentsJPanel msp = new ManageStudentsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("Manage Students Panel", msp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }

    private void seteditmode() {
        txtName.setEnabled(true);
        txtUsername.setEnabled(true);
        txtNUID.setEnabled(false);
        JOptionPane.showMessageDialog(this, "NUID cannot be edited");
        txtCreated.setEnabled(false);
        txtEmail.setEnabled(true);
        txtPhone.setEnabled(true);
      //  txtOfficeHours.setEnabled(true);  
    }

    private void resetpassword() {
        pwPassword.setVisible(true);
        pwConfirmPassword.setVisible(true);
        btnSavePw.setVisible(true);
        pwPassword.setEnabled(true);
        pwConfirmPassword.setEnabled(true);
        lblPassword.setVisible(true);
        lblConfirmPassword.setVisible(true);   
    }

    private void savepassword() {
    char[] passwordChars = pwPassword.getPassword(); 
    char[] confirmChars = pwConfirmPassword.getPassword(); 
    
    if (passwordChars == null || passwordChars.length == 0) { 
        JOptionPane.showMessageDialog(this, "Please enter a password"); 
        return; 
    } 
    if (!Arrays.equals(passwordChars, confirmChars)) { 
        JOptionPane.showMessageDialog(this, "Passwords don't match"); 
        return; 
    } 
    selecteduseraccount.setPassword(new String(passwordChars)); 
    selecteduseraccount.updatelastupdate(); 
    JOptionPane.showMessageDialog(this, "Password updated successfully"); 
    CardSequencePanel.remove(this); 
    ManageStudentsJPanel msp = new ManageStudentsJPanel(business, CardSequencePanel); 
    CardSequencePanel.add("Manage Students Panel", msp); 
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
     
    }        

    private String formatTimestamp(LocalDateTime timestamp) {
    if (timestamp == null) return "Never";
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy h:mm a");
    return timestamp.format(formatter);    
    }
  
}
