/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.EmployeeProfile;
import Business.Profiles.Profile;
import Business.Profiles.StudentProfile;
//import Business.Profiles.FacultyProfile; TO DO When Emmanuael creates it
import Business.UserAccounts.UserAccount;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class AdministerPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    UserAccount selecteduseraccount;
    Business business;

    public AdministerPersonJPanel(UserAccount sua, Business bz, JPanel jp) {

        CardSequencePanel = jp;
        this.business = bz;
        selecteduseraccount= sua;
        initComponents();
        
        populatefields();
        setviewmode();


    }

    //public void refreshTable() {

    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        pwPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        pwConfirmPassword = new javax.swing.JPasswordField();
        txtName = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        lblProfileType = new javax.swing.JLabel();
        txtCreated = new javax.swing.JTextField();
        txtLastLogin = new javax.swing.JTextField();
        txtLastUpdate = new javax.swing.JTextField();
        lblCreated = new javax.swing.JLabel();
        lblLastLogin = new javax.swing.JLabel();
        lblLastUpdate = new javax.swing.JLabel();
        cbxRole = new javax.swing.JComboBox<>();
        btnSavePw = new javax.swing.JButton();
        btnResetPw = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 430, 74, 23);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Manage Person Profile");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 550, 28);
        add(txtUsername);
        txtUsername.setBounds(140, 140, 140, 30);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(520, 250, 72, 23);

        lblName.setText("Name");
        add(lblName);
        lblName.setBounds(90, 200, 50, 20);

        lblUsername.setText("Username");
        add(lblUsername);
        lblUsername.setBounds(70, 150, 70, 20);
        add(pwPassword);
        pwPassword.setBounds(300, 370, 140, 30);

        lblPassword.setText("Password");
        add(lblPassword);
        lblPassword.setBounds(230, 380, 70, 20);

        lblConfirmPassword.setText("Confirm Password ");
        add(lblConfirmPassword);
        lblConfirmPassword.setBounds(190, 430, 110, 20);
        add(pwConfirmPassword);
        pwConfirmPassword.setBounds(300, 420, 140, 30);
        add(txtName);
        txtName.setBounds(140, 190, 140, 30);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit);
        btnEdit.setBounds(210, 250, 72, 23);

        lblProfileType.setText("Profile Type");
        add(lblProfileType);
        lblProfileType.setBounds(60, 100, 80, 20);
        add(txtCreated);
        txtCreated.setBounds(450, 90, 140, 30);
        add(txtLastLogin);
        txtLastLogin.setBounds(450, 140, 140, 30);
        add(txtLastUpdate);
        txtLastUpdate.setBounds(450, 190, 140, 30);

        lblCreated.setText("Created Date");
        add(lblCreated);
        lblCreated.setBounds(370, 100, 80, 16);

        lblLastLogin.setText("Last Login Date");
        add(lblLastLogin);
        lblLastLogin.setBounds(360, 150, 90, 16);

        lblLastUpdate.setText("Last Update Date");
        add(lblLastUpdate);
        lblLastUpdate.setBounds(350, 200, 100, 20);

        cbxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Registrar", "Faculty", "Student" }));
        add(cbxRole);
        cbxRole.setBounds(140, 92, 140, 30);

        btnSavePw.setText("Save password");
        btnSavePw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePwActionPerformed(evt);
            }
        });
        add(btnSavePw);
        btnSavePw.setBounds(487, 420, 110, 23);

        btnResetPw.setText("Reset Password");
        btnResetPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPwActionPerformed(evt);
            }
        });
        add(btnResetPw);
        btnResetPw.setBounds(340, 250, 120, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        updateuserinfo();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // Turn fields to editable
        seteditmode();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPwActionPerformed
        // Reset password sequence. Turns on hidden fields, sets them to editable.
        resetpassword();
    }//GEN-LAST:event_btnResetPwActionPerformed

    private void btnSavePwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePwActionPerformed
        // save password sequence (extract passwords, validate, save)
        savepassword();
    }//GEN-LAST:event_btnSavePwActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnResetPw;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSavePw;
    private javax.swing.JComboBox<String> cbxRole;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblCreated;
    private javax.swing.JLabel lblLastLogin;
    private javax.swing.JLabel lblLastUpdate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblProfileType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwConfirmPassword;
    private javax.swing.JPasswordField pwPassword;
    private javax.swing.JTextField txtCreated;
    private javax.swing.JTextField txtLastLogin;
    private javax.swing.JTextField txtLastUpdate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void populatefields() {
        //Get the Person for the user account
        Person person = selecteduseraccount.getAssociatedPersonProfile().getPerson();
        
        //Populate common fields
        txtName.setText(person.getPersonId());
        txtUsername.setText(selecteduseraccount.getUserLoginName());
        txtLastLogin.setText(formatTimestamp(selecteduseraccount.getLastlogintimestamp()));
        pwPassword.setVisible(false);
        pwConfirmPassword.setVisible(false);
        lblPassword.setVisible(false);
        lblConfirmPassword.setVisible(false);
       // txtCreated.setText(formatTimestamp(person.getCreatedtimestamp()));
        txtLastUpdate.setText(formatTimestamp(selecteduseraccount.getLastupdatetimestamp()));
        cbxRole.setSelectedItem(selecteduseraccount.getProfile().getRole()); 
        btnSavePw.setVisible(false);

        //Get Profile
        /*Populate any role-specific fields and attributes when they are created
        Profile profile = selecteduseraccount.getAssociatedPersonProfile();
        
        if (profile instanceof EmployeeProfile) {
        EmployeeProfile ep = (EmployeeProfile) profile;
        
        }
        
        else if (profile instanceof FacultyProfile) {
        FacultyProfile fp = (FacultyProfile) profile;
       
        }
        else if (profile instanceof StudentProfile) {
            StudentProfile sp = (StudentProfile) profile;
   
            }
        }*/
    }
    private void setviewmode() {
        cbxRole.setEnabled(false);
        txtName.setEnabled(false);
        txtUsername.setEnabled(false);
        txtLastLogin.setEnabled(false);
        txtLastUpdate.setEnabled(false);
        txtCreated.setEnabled(false);
    }

    private void updateuserinfo() {
    // Extract values from fields
        String name = txtName.getText().trim();
        String username = txtUsername.getText().trim();
        String role = (String) cbxRole.getSelectedItem();
    
    // Validate fields
        if (role==null){
            JOptionPane.showMessageDialog(this, "Please select a role");
            return;
        }
        
        if (name.isBlank() || username.isBlank()) {
            JOptionPane.showMessageDialog(this, "Name and Username are required");
            return;
        }
        
    // Update person name, user id, and role
        Person person = selecteduseraccount.getAssociatedPersonProfile().getPerson();
        person.setId(name);
        selecteduseraccount.setUsername(username);
        Profile profile = selecteduseraccount.getAssociatedPersonProfile();
        
        if (profile instanceof EmployeeProfile) {
            EmployeeProfile ep = (EmployeeProfile) profile;
            ep.setRole(role);  
        }

    // Update the "last updated" timestamp
        selecteduseraccount.updatelastupdate();
    
    // Show success and go back
        JOptionPane.showMessageDialog(this, "User account updated successfully");
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
            }
        

        private String formatTimestamp(LocalDateTime timestamp) {
        if (timestamp == null) {
            return "Never";
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy h:mm a");
        return timestamp.format(formatter);
        }

    private void seteditmode() {
        txtName.setEnabled(true);
        txtUsername.setEnabled(true);
        pwPassword.setEnabled(true);
        pwConfirmPassword.setEnabled(true);
        txtLastLogin.setEnabled(true);
        txtLastUpdate.setEnabled(true);
        txtCreated.setEnabled(true);
        cbxRole.setEnabled(true);
    }

    private void resetpassword() {
        pwPassword.setVisible(true);
        pwConfirmPassword.setVisible(true);
        btnSavePw.setVisible(true);
        pwPassword.setEnabled(true);
        pwConfirmPassword.setEnabled(true);
        lblPassword.setVisible(true);
        lblConfirmPassword.setVisible(true);
    }
    
    private void savepassword() {
        // Extract passwords
        char[] passwordChars = pwPassword.getPassword();
        char[] confirmChars = pwConfirmPassword.getPassword();
        
        //validate password isn't empty
        if (passwordChars == null || passwordChars.length == 0) {
            JOptionPane.showMessageDialog(this, "Please enter a password");
            return;
        }
    
        // If passwords are entered, validate they match
        if (passwordChars.length > 0) {
            if (!Arrays.equals(passwordChars, confirmChars)) {
                JOptionPane.showMessageDialog(this, "Passwords don't match");
                return;
            }
           
        // Update password
        String newPassword = new String(passwordChars);
        selecteduseraccount.setPassword(newPassword);
   
        // Update the "last updated" timestamp
        selecteduseraccount.updatelastupdate();
        
        }
        
        // Show success and go back
        JOptionPane.showMessageDialog(this, "Password updated successfully");
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
            }

}
