/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.UserAccounts.UserAccount;
import javax.swing.JPanel;

/**
 *h
 * @author kal bugrara
 */

public class AnalyticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    UserAccount selecteduseraccount;

    public AnalyticsJPanel(UserAccount sua, JPanel jp) {

        CardSequencePanel = jp;
        selecteduseraccount= sua;
        initComponents();
        //display user details here

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblPageTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActiveUsers = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCoursesPerSemester = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRevenue = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblStudentsPerCourse = new javax.swing.JTable();
        lblActiveUsers = new javax.swing.JLabel();
        lblCoursePerSemester = new javax.swing.JLabel();
        lblStudentsPerCourse = new javax.swing.JLabel();
        lblRevenue = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblPageTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblPageTitle.setText("Analytics");
        add(lblPageTitle);
        lblPageTitle.setBounds(21, 20, 550, 28);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 420, 100, 23);

        tblActiveUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Role", "Active Users"
            }
        ));
        jScrollPane1.setViewportView(tblActiveUsers);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 280, 130);

        tblCoursesPerSemester.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Semester", "Number of Courses"
            }
        ));
        jScrollPane2.setViewportView(tblCoursesPerSemester);

        add(jScrollPane2);
        jScrollPane2.setBounds(330, 90, 280, 130);

        tblRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student", "Tuition Paid"
            }
        ));
        jScrollPane3.setViewportView(tblRevenue);

        add(jScrollPane3);
        jScrollPane3.setBounds(330, 260, 280, 130);

        tblStudentsPerCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course", "Enrolled Students"
            }
        ));
        jScrollPane4.setViewportView(tblStudentsPerCourse);

        add(jScrollPane4);
        jScrollPane4.setBounds(30, 260, 280, 130);

        lblActiveUsers.setText("Total active users by role");
        add(lblActiveUsers);
        lblActiveUsers.setBounds(30, 70, 140, 16);

        lblCoursePerSemester.setText("Total courses offered per semester");
        add(lblCoursePerSemester);
        lblCoursePerSemester.setBounds(330, 70, 210, 16);

        lblStudentsPerCourse.setText("Total enrolled students per course");
        add(lblStudentsPerCourse);
        lblStudentsPerCourse.setBounds(30, 240, 220, 16);

        lblRevenue.setText("Tuition revenue summary");
        add(lblRevenue);
        lblRevenue.setBounds(330, 240, 190, 16);

        btnRefresh.setText("Refresh");
        add(btnRefresh);
        btnRefresh.setBounds(530, 410, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblActiveUsers;
    private javax.swing.JLabel lblCoursePerSemester;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblRevenue;
    private javax.swing.JLabel lblStudentsPerCourse;
    private javax.swing.JTable tblActiveUsers;
    private javax.swing.JTable tblCoursesPerSemester;
    private javax.swing.JTable tblRevenue;
    private javax.swing.JTable tblStudentsPerCourse;
    // End of variables declaration//GEN-END:variables

    

}
