/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *h
 * @author kal bugrara
 */


public class ManageStudentsJPanel extends javax.swing.JPanel {

  
    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;
    UserAccountDirectory users;

    public ManageStudentsJPanel(Business bz, JPanel jp) {

        CardSequencePanel = jp;
        this.business = bz;
        this.users = business.getUserAccountDirectory();
        initComponents();
        populatetable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPageTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        cbxSearchType = new javax.swing.JComboBox<>();
        lblSearchBy = new javax.swing.JLabel();
        txtSearchField = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblPageTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblPageTitle.setText("Student Accounts");
        add(lblPageTitle);
        lblPageTitle.setBounds(21, 20, 550, 28);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 420, 100, 23);

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "NUID", "Email", "Department", "Academic Status", "CellNo"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 140, 540, 190);

        cbxSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By Name", "By Department", "By NUID" }));
        add(cbxSearchType);
        cbxSearchType.setBounds(140, 100, 100, 22);

        lblSearchBy.setText("Search By");
        add(lblSearchBy);
        lblSearchBy.setBounds(140, 80, 70, 16);

        txtSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFieldActionPerformed(evt);
            }
        });
        add(txtSearchField);
        txtSearchField.setBounds(260, 100, 190, 22);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(520, 100, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFieldActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbxSearchType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblSearchBy;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtSearchField;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
        //declare the table
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();

        //Clear all rows starting with the end
        int rc = tblStudents.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tblStudents.getModel()).removeRow(i);
        }
        
        //get the directory of all user accoutns in the system
        UserAccountDirectory uad = business.getUserAccountDirectory();
                
        //loop through the directory of all users
        for (UserAccount ua : uad.getUserAccountList()) {
            
        //filter to only show Student Accounts
        if (!(ua.getAssociatedPersonProfile() instanceof StudentProfile)) {
            continue;
        }
        //cast to specific StudentProfile to access student-specific methods
        StudentProfile bizStudent = (StudentProfile) ua.getAssociatedPersonProfile();
        
        // get university-side profile through the bridge
        university.Persona.StudentProfile uniStudent = bizStudent.getUniversityProfile();

        //create local variables for student fields
        String name     = bizStudent.getPerson().getFullname();
        String nuid     = bizStudent.getPerson().getPersonId();
        String email    = bizStudent.getEmail() != null ? bizStudent.getEmail() : "";
        String dept     = "Information Systems"; // all students in same dept
        String standing = "";
        String cellno   = bizStudent.getPhone() != null ? bizStudent.getPhone() : "";
            
        // Academic standing requires an active transcript
        if (uniStudent != null) {                                                   //if the business StudentProfile has an equivalent University Persona Profile
            university.Persona.Transcript transcript = uniStudent.getTranscript();  //get the transcript
            java.util.ArrayList<String> semesters = transcript.getSemesters();      //get the semesters from the transcript
            if (!semesters.isEmpty()) {                                             //if semesters is not null, call getAcademicStanding method            
                String latestSemester = semesters.get(semesters.size() - 1);
                standing = transcript.getAcademicStanding(latestSemester);
            }
        }
        //pack all values into an array in the same order as the table columns and add as a new row
        Object[] row = new Object[]{name, nuid, email, dept, standing, cellno};
        model.addRow(row);
    }
}
        

    
    
    private void search() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

}
