/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Person.PersonDirectory;
import Business.Profiles.RegistrarProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *h
 * @author kal bugrara
 */


public class ManageEmployeesJPanel extends javax.swing.JPanel {

  
    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;
    UserAccountDirectory users;
    PersonDirectory persondirectory;

    public ManageEmployeesJPanel(Business bz, JPanel jp) {

        CardSequencePanel = jp;
        this.business = bz;
        this.users = business.getUserAccountDirectory();
        this.persondirectory = business.getPersonDirectory();
        initComponents();
        
        
        
    // Override table model to add hidden UserAccount column
        tblEmployees.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"Name", "NUID", "Email", "Department", "CellNo", "Office Hours", "ua"}
        )); 
        
    // Add hidden column to store ua object
    // Hide the last column — it holds the UserAccount object, not for display
        tblEmployees.getColumnModel().getColumn(6).setMinWidth(0);
        tblEmployees.getColumnModel().getColumn(6).setMaxWidth(0);
        tblEmployees.getColumnModel().getColumn(6).setWidth(0);        
        populatetable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPageTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblPageTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblPageTitle.setText("Employee Accounts");
        add(lblPageTitle);
        lblPageTitle.setBounds(21, 20, 550, 28);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 420, 100, 23);

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "NUID", "Email", "Department", "CellNo", "Office Hours"
            }
        ));
        jScrollPane1.setViewportView(tblEmployees);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 800, 190);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(510, 420, 72, 23);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit);
        btnEdit.setBounds(40, 290, 72, 23);

        btnSave.setText("Save");
        add(btnSave);
        btnSave.setBounds(130, 290, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    int row = tblEmployees.getSelectedRow();
    if(row <0){
        JOptionPane.showMessageDialog(this, "Please select a row to continue");
        return;
    }
    // Retrieve UserAccount from hidden column 7
    UserAccount u = (UserAccount) tblEmployees.getValueAt(row, 6);
    if (u == null) return;

    users.removeUser(u);
    populatetable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblEmployees.getSelectedRow();
        
        if(selectedRow >=0){
            selecteduseraccount = (UserAccount) tblEmployees.getValueAt(selectedRow, 6);
        }
        
        if(selecteduseraccount==null) 
            return;
            AdministerPersonJPanel mpjp = new AdministerPersonJPanel (selecteduseraccount,business, CardSequencePanel);
            CardSequencePanel.add(mpjp);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);        
        
        
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
        cleartable();
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        
        //get the directory of all user accoutns in the system
        UserAccountDirectory uad = business.getUserAccountDirectory();
                
        //loop through the directory of all users
        for (UserAccount ua : uad.getUserAccountList()) {
            
        //filter to only show Student Accounts
        if (!(ua.getAssociatedPersonProfile() instanceof RegistrarProfile)) {
            continue;
        }
        //cast to specific StudentProfile to access student-specific methods
        RegistrarProfile bizEmployee = (RegistrarProfile) ua.getAssociatedPersonProfile();
        
        addrowtotable(model, bizEmployee);
    }

}

    
    //Helper Methods
    private void cleartable() {
    //declare the table
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();

    //Clear all rows starting with the end
        int rc = tblEmployees.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tblEmployees.getModel()).removeRow(i);
        }
    }
    
    private void addrowtotable(DefaultTableModel model, RegistrarProfile bizEmployee) {
        
    //extract all column values from the profile
        String name     = bizEmployee.getPerson().getFullname();
        String nuid     = bizEmployee.getPerson().getPersonId();
        String email    = bizEmployee.getEmail() != null ? bizEmployee.getEmail() : "";
        String dept     = "Information Systems";
        String cellno   = bizEmployee.getPhone() != null ? bizEmployee.getPhone() : "";
        String officehrs = bizEmployee.getOfficeHours();                            
        
    // Store nuid as an object to use on the hidden column
        UserAccount ua = users.findUserAccount(nuid);
    
    // Package into array matching column order: Name, NUID, Email, Dept, Standing, CellNo
        Object[] row = new Object[]{name, nuid, email, dept, cellno, officehrs, ua};                 ///TO DO Add Office hours once it exists
        model.addRow(row);
    }
    
    private void tblEmployeesMousePressed(java.awt.event.MouseEvent evt) {                                              
        // Extracts the row (user account) in the table that is selected by the user
        int size = tblEmployees.getRowCount();
        int selectedrow = tblEmployees.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selecteduseraccount = (UserAccount) tblEmployees.getValueAt(selectedrow, 6);
        if (selecteduseraccount == null) {
            return;
        
        
        }        
    }
    


}
