/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Person.PersonDirectory;
import Business.Profiles.EmployeeDirectory;
import Business.Profiles.EmployeeProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *h
 * @author kal bugrara
 */

public class ManageFacultyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;
    UserAccountDirectory users;
    PersonDirectory persondirectory;

   

    public ManageFacultyJPanel(Business bz, JPanel jp) {

        CardSequencePanel = jp;
        this.business = bz;
        this.users = business.getUserAccountDirectory();
        this.persondirectory = business.getPersonDirectory();
        initComponents();
        
            // Override table model to add hidden UserAccount column
        tblFaculty.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"Name", "NUID", "Email", "Department", "CellNo", "Office Hours", "ua"}
        )); 
        // Add hidden column to store ua object
    // Hide the last column — it holds the UserAccount object, not for display
        tblFaculty.getColumnModel().getColumn(6).setMinWidth(0);
        tblFaculty.getColumnModel().getColumn(6).setMaxWidth(0);
        tblFaculty.getColumnModel().getColumn(6).setWidth(0);        
        populatetable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPageTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFaculty = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        cbxSearchType = new javax.swing.JComboBox<>();
        lblSearchBy = new javax.swing.JLabel();
        txtSearchField = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblPageTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblPageTitle.setText("Faculty Accounts");
        add(lblPageTitle);
        lblPageTitle.setBounds(21, 20, 550, 28);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(50, 420, 100, 23);

        tblFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "NUID", "Email", "Department", "CellNo", "Office Hours"
            }
        ));
        jScrollPane1.setViewportView(tblFaculty);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 140, 550, 190);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(510, 420, 72, 23);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit);
        btnEdit.setBounds(50, 350, 72, 23);

        btnSave.setText("Save");
        add(btnSave);
        btnSave.setBounds(140, 350, 72, 23);

        cbxSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By Name", "By Department", "By NUID" }));
        cbxSearchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSearchTypeActionPerformed(evt);
            }
        });
        add(cbxSearchType);
        cbxSearchType.setBounds(140, 100, 100, 22);

        lblSearchBy.setText("Search By");
        add(lblSearchBy);
        lblSearchBy.setBounds(140, 80, 70, 16);

        txtSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFieldActionPerformed(evt);
            }
        });
        add(txtSearchField);
        txtSearchField.setBounds(260, 100, 190, 22);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(520, 100, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int row = tblFaculty.getSelectedRow();
        if(row <0){
            JOptionPane.showMessageDialog(this, "Please select a row to continue");
            return;
        }
        // Retrieve UserAccount from hidden column 7
        UserAccount u = (UserAccount) tblFaculty.getValueAt(row, 6);
        if (u == null) return;

        users.removeUser(u);
        populatetable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFaculty.getSelectedRow();

        if(selectedRow >=0){
            selecteduseraccount = (UserAccount) tblFaculty.getValueAt(selectedRow, 6);
        }

        if(selecteduseraccount==null)
        return;
        AdministerFacultyJPanel afjp = new AdministerFacultyJPanel (selecteduseraccount,business, CardSequencePanel);
        CardSequencePanel.add("Administer Faculty Panel",afjp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnEditActionPerformed

    private void cbxSearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSearchTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSearchTypeActionPerformed

    private void txtSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFieldActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbxSearchType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblSearchBy;
    private javax.swing.JTable tblFaculty;
    private javax.swing.JTextField txtSearchField;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
        cleartable();
        DefaultTableModel model = (DefaultTableModel) tblFaculty.getModel();
        
        //get the directory of all user accoutns in the system
        UserAccountDirectory uad = business.getUserAccountDirectory();
                
        //loop through the directory of all users
        for (UserAccount ua : uad.getUserAccountList()) {
            
        //filter to only show Faculty Accounts
        if (!(ua.getAssociatedPersonProfile() instanceof EmployeeProfile)) {
            continue;
        }
        EmployeeProfile ep = (EmployeeProfile) ua.getAssociatedPersonProfile();
        if(!ep.getRole().equals("Faculty")){
            continue;
        }
             
        addrowtotable(model, ep);    
    }
}

    private void cleartable() {
        //declare the table
        DefaultTableModel model = (DefaultTableModel) tblFaculty.getModel();

    //Clear all rows starting with the end
        int rc = tblFaculty.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tblFaculty.getModel()).removeRow(i);
        }
    
    }

    private void addrowtotable(DefaultTableModel model, EmployeeProfile ep) {
    //Get University package Facultyprofile through the bridge
    university.Persona.Faculty.FacultyProfile uniFaculty = ep.getUniversityProfile();

    //extract all column values from the profile
        String name     = ep.getPerson().getFullname();
        String nuid     = ep.getPerson().getPersonId();
        String email    = ep.getEmail() != null ? ep.getEmail() : "";
        String dept     = "Information Systems";
        String cellno   = ep.getPhone() != null ? ep.getPhone() : "";
        String officehrs = "";                            
        
    // Store nuid as an object to use on the hidden column
        UserAccount ua = users.findUserAccount(nuid);
    
    // Package into array matching column order: Name, NUID, Email, Dept, Standing, CellNo
        Object[] row = new Object[]{name, nuid, email, dept, cellno, officehrs, ua};                 
        model.addRow(row);    
    }
    
    private void tblFacultyMousePressed(java.awt.event.MouseEvent evt) {                                              
        // Extracts the row (user account) in the table that is selected by the user
        int size = tblFaculty.getRowCount();
        int selectedrow = tblFaculty.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selecteduseraccount = (UserAccount) tblFaculty.getValueAt(selectedrow, 6);
        if (selecteduseraccount == null) {
            return;
        
        
        }        
    }

    private void search() {
        cleartable();
        DefaultTableModel model = (DefaultTableModel) tblFaculty.getModel();
        
        String searchtype = (String) cbxSearchType.getSelectedItem();
        String searchterm = txtSearchField.getText().trim();
        
        if(searchterm.isEmpty()){
            populatetable();
            return;
        }
        
        EmployeeDirectory ed = business.getEmployeeDirectory();
        
        if(searchtype.equals("By NUID")){
            EmployeeProfile foundid = ed.findEmployee(searchterm);
            
            if(foundid !=null){
                UserAccount ua = users.findUserAccount(foundid.getPerson().getPersonId());
                addrowtotable(model,foundid);
                }
            }else if (searchtype.equals("By Name")){
                ArrayList<EmployeeProfile> results = ed.searchByName(searchterm);
                
                for (EmployeeProfile ep: results){
                    UserAccount ua = users.findUserAccount(ep.getPerson().getPersonId());
                    addrowtotable(model,ep);
                }
            }else if(searchtype.equals("By Department")){     //TO DO Need to discuss populating multiple departments
        

        populatetable();
    
        }
    }
    
    
}
