/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import university.CourseSchedule.CourseLoad;
import university.CourseSchedule.SeatAssignment;
import university.Department.Department;

/**
 *
 * @author Hank_Local
 */
public class CourseWorkJPanel extends javax.swing.JPanel {
    
    //HL: business references 
    private Business business; //HL: added import using AltEnter
    private StudentProfile student; //HL: added import using AltEnter
    private JPanel CardSequencePanel; //HL: added import using AltEnter
    
    //HL: university refrence for student profile CourseLoad access
    private university.Persona.StudentProfile uniStudentProfile;
    
    //HL: seeded semester in ConfigureABusiness.java 
    private static final String CURRENT_SEMESTER = "Fall 2025";

    /**
     * Creates new form CourseWorkJPanel
     */
    public CourseWorkJPanel(Business b, StudentProfile spp, JPanel clp) {
        initComponents();
        business = b;
        student = spp;
        CardSequencePanel = clp;
        
        //HL: getter for StudentProfile (university)
        Department dept = business.getDepartment(); //HL: added import using AltEnter
        if (dept != null){
            uniStudentProfile = dept.getStudentDirectory().findStudent(student.getPerson().getPersonId()); 
        }
        
        //HL: JTable non-editable 
        tblCourseWork.setDefaultEditor(Object.class, null);
        tblCourseWork.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); //HL: added import using AltEnter
        
        //HL: when a specific row is selected, load existing submission note into the text field 
        tblCourseWork.getSelectionModel().addListSelectionListener( e -> {
            if (!e.getValueIsAdjusting()){
                loadSubmissionNote(); //HL: created method using AltEnter
            }
        }); 
        loadPanel(); //HL: created method using AltEnter
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        lblSemesterValue = new javax.swing.JLabel();
        lblGPA = new javax.swing.JLabel();
        lblGPAValue = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        lblCreditsValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseWork = new javax.swing.JTable();
        lblNote = new javax.swing.JLabel();
        fieldNote = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("Course Work & Progress Tracking");

        lblSemester.setText("Current Semester: ");

        lblSemesterValue.setText("--");

        lblGPA.setText("Current GPA: ");

        lblGPAValue.setText("--");

        lblCredits.setText("Credits (This Semester):");

        lblCreditsValue.setText("--");

        tblCourseWork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Credits", "Current Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourseWork);

        lblNote.setText("Assignment Notes:");

        btnSubmit.setText("Submit Assignment");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblStatus.setText(" ");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGPA)
                            .addComponent(lblSemester)
                            .addComponent(lblCredits))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSemesterValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGPAValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCreditsValue, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSubmit)
                            .addComponent(fieldNote, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(lblSemesterValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGPA)
                    .addComponent(lblGPAValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredits)
                    .addComponent(lblCreditsValue))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNote)
                    .addComponent(fieldNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        //HL: added by double-clicking Submit Assignment Button in Form editor 
        submitAssignment();
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //HL: added by double-clicking Back Button in Form editor
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel); //HL: added import using AltEnter 
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField fieldNote;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblCreditsValue;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblGPAValue;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblSemesterValue;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCourseWork;
    // End of variables declaration//GEN-END:variables

    
    //HL: if a course row is selected, adds any existing notes to fieldNote
    private void loadSubmissionNote() {
        int selectedRow = tblCourseWork.getSelectedRow();
        if (selectedRow < 0) return;

        CourseLoad cl = uniStudentProfile.getCourseLoadBySemester(CURRENT_SEMESTER);
        if (cl == null) return;
        
        //HL: match row to SeatAssignment by CourseId 
        String courseId = (String) ((DefaultTableModel) tblCourseWork.getModel()).getValueAt(selectedRow, 0);
        
        for (SeatAssignment sa : cl.getSeatAssignments()){
            if (sa.getAssociatedCourse().getCOurseNumber().equals(courseId)){
                fieldNote.setText(sa.getSubmissionNote());
                break; 
            }
        }
        
    }

    
    //HL: loads table, semester, GPA, and credits in UI 
    private void loadPanel() {
        if (uniStudentProfile == null) return;
        
        //HL: set semester value label - Fall 2025 or other 
        lblSemesterValue.setText(CURRENT_SEMESTER);
        
        //HL: get course load for the semester for a specific studentprofile 
        CourseLoad cl = uniStudentProfile.getCourseLoadBySemester(CURRENT_SEMESTER); //HL: added import using AltEnter 
        
        //HL: null check for courseload
        if (cl == null){
            lblGPAValue.setText("0.00");
            lblCreditsValue.setText("0");
            lblStatus.setForeground(java.awt.Color.GRAY);
            lblStatus.setText("No courses in " + CURRENT_SEMESTER);
            return;
        }
        
        //HL: add GPA and total credits to lblGPAValue and lblCreditsValue 
        lblGPAValue.setText(String.format("%.2f", cl.getSemesterGPA()));
        lblCreditsValue.setText(String.valueOf(cl.getTotalCredits()));
        
        //HL: populate table 
        loadCourseTable(cl); //HL: added method using AltEnter
        
    }

    
    //HL: method to populate JTable with a studentprofile's enrolled courses, grades, and total credits
    private void loadCourseTable(CourseLoad cl) {
        DefaultTableModel model = (DefaultTableModel) tblCourseWork.getModel(); //HL: added import using AltEnter
        model.setRowCount(0); //HL: clear rows
        
        for (SeatAssignment sa : cl.getSeatAssignments()){ //HL: added import using AltEnter 
            String courseId = sa.getAssociatedCourse().getCOurseNumber();
            String courseName = sa.getAssociatedCourse().getName();
            int credits = sa.getCreditHours();
            String grade = sa.getGrade(); //HL: n/a if not graded 
            
            model.addRow(new Object[]{courseId, courseName, credits, grade});
        }
        
    }
    
    //HL: method for student to submit the assignment note for a selected course, ensures a row is selected & note field has entry 
    private void submitAssignment(){
        int selectedRow = tblCourseWork.getSelectedRow();
        
        //HL: check if row is selected before submitting 
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Select a course to submit an assignment for.");
            return; 
        }
        String note = fieldNote.getText().trim();
        
        //HL: check if fieldNote is empty, require an entry before submission 
        if (note.isEmpty()){
            JOptionPane.showMessageDialog(this, "You must enter a note prior to submission.");
            return; 
        }
        
        if (uniStudentProfile == null) return;
        CourseLoad cl = uniStudentProfile.getCourseLoadBySemester(CURRENT_SEMESTER);
        if (cl == null) return;
        
        //HL: identify SeatAssignment and save submission note 
        String courseId = (String)((DefaultTableModel) tblCourseWork.getModel()).getValueAt(selectedRow, 0); 
        boolean submitted = false;
        for (SeatAssignment sa : cl.getSeatAssignments()){
            if (sa.getAssociatedCourse().getCOurseNumber().equals(courseId)){
                sa.submitAssignment(note);
                submitted = true;
                break;
            }
        }
        if (submitted){
            lblStatus.setForeground(new java.awt.Color(0, 128, 0));
            lblStatus.setText("Assignment submitted for " + courseId);
            fieldNote.setText(""); //HL: clear fieldNote 
        } else {
            lblStatus.setForeground(java.awt.Color.RED);
            lblStatus.setText("Submission failed, course not found.");
        }
        
    }
    
}
