/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import university.CourseSchedule.CourseLoad;
import university.CourseSchedule.CourseOffer;
import university.CourseSchedule.CourseSchedule;
import university.CourseSchedule.SeatAssignment;
import university.Department.Department;



/**
 *
 * @author Hank_Local
 */
public class CourseRegistrationJPanel extends javax.swing.JPanel {
    
    //HL: Business references 
    private Business business; // HL: added import using AltEnter
    private StudentProfile student; // HL: added import using AltEnter
    private JPanel CardSequencePanel; // HL: added import using AltEnter
    
    //HL: University layer StudentProfile for CourseLoad & Transcript access 
    //HL: To-Do:  confirm getDepartment() getter existes on Business.java with Polina ****************************
    private university.Persona.StudentProfile uniStudentProfile;
    private CourseSchedule currentSchedule; // HL: added import using AltEnter
    
    //HL: match to the semester string used in ConfigureABusiness.java ********************confirm w/ team what semester we want to use
    private static final String CURRENT_SEMESTER = "Fall 2025"; 

    /**
     * Creates new form CourseRegistrationJPanel
     */
    public CourseRegistrationJPanel(Business b, StudentProfile spp, JPanel clp) {
        initComponents();
        business = b;
        student = spp;
        CardSequencePanel = clp;
        
        //HL: get university student profile & course schedule 
        //HL: To-Do: confirm getDepartment() getter existes on Business.java with Polina ****************************
        Department dept = business.getDepartment(); //HL: added import using AltEnter  
        if (dept != null){
            uniStudentProfile = dept.getStudentDirectory().findStudent(student.getPerson().getPersonId()); 
            currentSchedule = dept.getCourseSchedule(CURRENT_SEMESTER); 
        }
        
        //HL: Table - non-editable and select a single row 
        tblCourse.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); //HL: added import using AltEnter
        ((DefaultTableModel) tblCourse.getModel()).setRowCount(0); //HL: added import using AltEnter
        loadAllCourses(); // HL: created method using AltEnter - populates table when first opening panel
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        comboSearch = new javax.swing.JComboBox<>();
        fieldSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        btnEnroll = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        btnPayTuition = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("Course Registration");

        lblSearch.setText("Search By: ");

        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course ID ", "Teacher Name ", "Course Name" }));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Teacher", "Credits", "Available Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourse);

        lblStatus.setText("Status");
        lblStatus.setMaximumSize(new java.awt.Dimension(500, 20));
        lblStatus.setMinimumSize(new java.awt.Dimension(500, 20));
        lblStatus.setPreferredSize(new java.awt.Dimension(500, 20));

        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnDrop.setText("Drop");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        btnPayTuition.setText("Pay Tuition");
        btnPayTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayTuitionActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnroll)
                        .addGap(18, 18, 18)
                        .addComponent(btnDrop)
                        .addGap(18, 18, 18)
                        .addComponent(btnPayTuition))
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch)
                            .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(comboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnroll)
                    .addComponent(btnDrop)
                    .addComponent(btnPayTuition))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        performSearch();
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        // TODO add your handling code here:
        
        enrollInCourse();
        
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        // TODO add your handling code here:
        
        dropCourse();
        
    }//GEN-LAST:event_btnDropActionPerformed

    private void btnPayTuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayTuitionActionPerformed
        // TODO add your handling code here:
        //HL: navigates student to TuitionPaymentJPanel
        goToTuition(); 
                
    }//GEN-LAST:event_btnPayTuitionActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        goBack();
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnPayTuition;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCourse;
    // End of variables declaration//GEN-END:variables

    //HL: loads all course offerings for the current semester into JTable 
    private void loadAllCourses() {
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
        model.setRowCount(0); // clear rows
        
        if (currentSchedule == null){
            lblStatus.setForeground(java.awt.Color.RED);
            lblStatus.setText("Course schedule not found for " + CURRENT_SEMESTER);
            return;
        }
        for (CourseOffer co : currentSchedule.getSchedule()){ //needs method in CourseSchedule from Lanre, not HL responsibility 
            addRowtoTable(co); 
        }
    }
    
    //HL: helper method, builds a row from CourseOffer & adds to table (Lanre)  
    private void addRowtoTable(CourseOffer co){
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
        String courseId   = co.getCourseNumber();
        String courseName = co.getSubjectCourse().getName(); 
        String teacher = (co.getFacultyProfile() != null) ? co.getFacultyProfile().getPerson().getPersonId() : "TBA"; 
        int credits = co.getCreditHours(); 
        
        //HL: TO DO "See Registrat" needs to be replaced once Lanre mreges getEnrolledCount() to CourseOffer so available seats can be calculated
        String seats = "See registrar"; 
        model.addRow(new Object[]{courseId, courseName, teacher, credits, seats}); 
        
    }
    
    //HL: search method by comboSearch selection (Course ID, Teacher Name, Course Name)
    private void performSearch(){
        String query = fieldSearch.getText().trim().toLowerCase();
        String searchType = (String) comboSearch.getSelectedItem();
        
        //HL: if search box is empty, table reverts to show all courses 
        if (query.isEmpty()){
            loadAllCourses();
            lblStatus.setText(" ");
            return; 
        }
        if (currentSchedule == null) return; 
        
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
        model.setRowCount(0); // clear before repopulating
        
        for (CourseOffer co : currentSchedule.getSchedule()){ //needs method in CourseSchedule from Lanre, not HL responsibility
            boolean match = false; 
            
            //HL: combo box selection - search by Course ID
            if (searchType.equals("Course ID")){
                match = co.getCourseNumber().toLowerCase().contains(query);
            }
            //HL: combo box selection - search by Teacher name 
            else if (searchType.equals("Teacher Name")){
                if (co.getFacultyProfile() != null){
                    String name = co.getFacultyProfile().getPerson().getPersonId().toLowerCase();
                    match = name.contains(query); 
                }
            }
            //HL: combo box selection - search by Course Name 
            else if (searchType.equals("Course Name")){
                match = co.getSubjectCourse().getName().toLowerCase().contains(query);
            }
            if (match) addRowtoTable(co); //HL: if match is found add, add course offer to table 
        }
        //HL: if there are no matches, inform student in Status 
        if (model.getRowCount() == 0){
            lblStatus.setForeground(java.awt.Color.RED);
            lblStatus.setText("No matching courses found: " + fieldSearch.getText().trim()); 
        } else {
            lblStatus.setText(" ");
        }
    }
    
    //HL: method to enroll a student in a course selected in the JTable 
    private void enrollInCourse(){
        int selectedRow = tblCourse.getSelectedRow();
        //HL: check if row is selected, return error message if null 
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a course for enrollment."); //HL: added import using AltEnter 
            return; 
        }
        if (currentSchedule == null || uniStudentProfile == null) return; 
        
        String courseId = (String) ((DefaultTableModel) tblCourse.getModel()).getValueAt(selectedRow, 0); 
        CourseOffer co = currentSchedule.getCourseOfferByNumber(courseId);
        if (co == null) return;
        
        //HL: To-Do********************
        //HL: remove comments once Lanre merges isAtCapacity() to CourseOffer.java 
        /*if (co.isAtCapacity()){
            JOptionPane.showMessageDialog(this, "Course is full.");
            return; 
        }*/
        
        //HL: gets existing or creates new course load for semester 
        CourseLoad cl = uniStudentProfile.getCurrentCourseLoad(); //HL: added import using AltEnter 
        if (cl == null){
            cl = uniStudentProfile.newCourseLoad(CURRENT_SEMESTER);
        }
        
        //HL: caps student @ 8-credits per semester per assignment instructions 
        int currentCredits = cl.getTotalCredits();
        int newCredits     = co.getCreditHours();
        if (currentCredits + newCredits > 8){ 
            JOptionPane.showMessageDialog(this, "Cannot enroll:" + " adding these exceeds the 8-credit limit" + "Current credits: " + currentCredits);
            return; 
        }
        
        //HL: if not at credit limit, enroll student in course & assign seat 
        SeatAssignment sa = co.assignEmptySeat(cl); //HL: added import using AltEnter 
        //HL: if course is full... 
        if (sa == null){
            JOptionPane.showMessageDialog(this, "No seats available, cannot enroll");
            return; 
        }
        
        //HL: on successful enrollment, add course price to student's tuition balance 
        uniStudentProfile.setBalance(uniStudentProfile.getBalance() + co.getSubjectCourse().getCoursePrice()); //HL: added getBalance() to StudentProfile.java 
        lblStatus.setForeground(new java.awt.Color(0, 128, 0));
        lblStatus.setText("Successfully enrolled in " + courseId); 
        loadAllCourses(); //HL: refreshes table 
        
    }
    
    //HL: method for the Student to drop a course (selected in JTable) from their course load & refund if already paid 
    private void dropCourse(){
        int selectedRow = tblCourse.getSelectedRow(); 
        
        //HL: if row isn't selected
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Must select course before dropping.");
            return; 
        }
        if (uniStudentProfile == null) return; 
        
        String courseId = (String) ((DefaultTableModel) tblCourse.getModel()).getValueAt(selectedRow, 0); 
        
        CourseLoad cl = uniStudentProfile.getCurrentCourseLoad();
        if (cl == null){
            JOptionPane.showMessageDialog(this, "You are currently not enrolled in a course this semester");
            return; 
        }
        
        //HL: Find SeatAssignment for selected course 
        SeatAssignment toRemove = null; 
        for (SeatAssignment sa : cl.getSeatAssignments()){
            if (sa.getAssociatedCourse().getCOurseNumber().equals(courseId)){
                toRemove = sa;
                break; 
            }
        }
        if (toRemove == null){
            JOptionPane.showMessageDialog(this, "You aren't enrolled in " + courseId); 
            return; 
        }
        
        //HL: issue refund 
        if (uniStudentProfile.isTuitionPaid()){
            double refundAmt = toRemove.getAssociatedCourse().getCoursePrice();
            uniStudentProfile.refund(refundAmt, courseId);
            lblStatus.setForeground(new java.awt.Color(0, 128, 0));
            lblStatus.setText("Dropped " + courseId + " - refunded $" + String.format("%.2f", refundAmt) + " successfully.");
        } else{
            lblStatus.setForeground(java.awt.Color.RED);
            lblStatus.setText("Dropped " + courseId);
        }
        //HL: remove seat assignment from student's course load 
        cl.getSeatAssignments().remove(toRemove);
        loadAllCourses(); //HL: refreshes table 
        
    }
    
    //HL: navigate student to Tuition Payment JPanel **********not yet created*********
    private void goToTuition(){ 
        
        TuitionPaymentJPanel panel = new TuitionPaymentJPanel(business, student, CardSequencePanel); 
        CardSequencePanel.add("Tuition", panel);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel); //HL: added import using AltEnter 
        
    }
    
    //HL: return student to previous panel 
    private void goBack(){
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }
    
    
}
