/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JPanel;
import university.CourseSchedule.SeatAssignment;
import university.Department.Department;

/**
 *
 * @author Hank_Local
 */
public class GraduationAuditJPanel extends javax.swing.JPanel {
    
    //HL: business references
    private Business business; //HL: added import using AltEnter
    private StudentProfile student; //HL: added import using AltEnter
    private JPanel CardSequencePanel; //HL: added import using AltEnter
    //HL: university reference to student profile for transcript access
    private university.Persona.StudentProfile uniStudentProfile;
    
    //HL: Student requirements for graduation (directly from assignment instructions) 
    private static final int REQUIRED_CREDITS = 32;
    private static final String CORE_COURSE_ID = "INFO5100"; //HL: INFO5100 string from ConfigureABusiness.java
            
            

    /**
     * Creates new form GraduationAuditJPanel
     */
    public GraduationAuditJPanel(Business b, StudentProfile spp, JPanel clp) {
        initComponents();
        business = b;
        student = spp;
        CardSequencePanel = clp;
        
        //HL: get university student profile
        Department dept = business.getDepartment(); //HL: added import using AltEnter
        if (dept != null){
            uniStudentProfile = dept.getStudentDirectory().findStudent(student.getPerson().getPersonId()); 
        }
        
        runAudit(); //HL: created method using AltEnter
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCreditsEarned = new javax.swing.JLabel();
        lblCreditsEarnedValue = new javax.swing.JLabel();
        lblCreditsRequired = new javax.swing.JLabel();
        lblCreditsRequiredValue = new javax.swing.JLabel();
        lblCoreReq = new javax.swing.JLabel();
        lblCoreReqValue = new javax.swing.JLabel();
        lblReadiness = new javax.swing.JLabel();
        lblReadinessValue = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("Student Graduation Audit");

        lblCreditsEarned.setText("Total Credits Earned: ");

        lblCreditsEarnedValue.setText("--");

        lblCreditsRequired.setText("Credits Required: ");

        lblCreditsRequiredValue.setText("32");

        lblCoreReq.setText("INFO5100 Core Requirement: ");

        lblCoreReqValue.setText("--");

        lblReadiness.setText("Graduation Status: ");

        lblReadinessValue.setText("--");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCreditsRequired, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCreditsEarned, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCoreReq)
                                    .addComponent(lblReadiness)
                                    .addComponent(btnRefresh))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCreditsEarnedValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCreditsRequiredValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCoreReqValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReadinessValue, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnBack)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblTitle)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditsEarned)
                    .addComponent(lblCreditsEarnedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditsRequiredValue)
                    .addComponent(lblCreditsRequired, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoreReq)
                    .addComponent(lblCoreReqValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReadiness)
                    .addComponent(lblReadinessValue))
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        //HL: added by double-clicking button in form editor, runs graduation audit 
        runAudit();
        
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //HL: added by double-clicking button in form editor
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel); //HL: added import using AltEnter 
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel lblCoreReq;
    private javax.swing.JLabel lblCoreReqValue;
    private javax.swing.JLabel lblCreditsEarned;
    private javax.swing.JLabel lblCreditsEarnedValue;
    private javax.swing.JLabel lblCreditsRequired;
    private javax.swing.JLabel lblCreditsRequiredValue;
    private javax.swing.JLabel lblReadiness;
    private javax.swing.JLabel lblReadinessValue;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    private void runAudit() {
        if (uniStudentProfile == null){
            lblReadinessValue.setText("Student profile not found");
            return;
        }
        
        //HL: get student's seat assignments from all semesters 
        ArrayList<SeatAssignment> allCourses = uniStudentProfile.getCourseList(); //HL: added import using AltEnter
        
        //HL: calculate earned credits based on seat assignments 
        int totalCredits = 0;
        boolean coreCompleted = false;
        for (SeatAssignment sa : allCourses){
            totalCredits += sa.getCreditHours();
            //HL: checks if INFO5100 (core course requirement per instructions) has been completed 
            if (sa.getAssociatedCourse().getCOurseNumber().equals(CORE_COURSE_ID)){
                coreCompleted = true; 
            }
            
        }
        //HL: display total credits earned in UI 
        lblCreditsEarnedValue.setText(String.valueOf(totalCredits));
        
        //HL: update status of "INFO5100 Core Requirement" in UI 
        if (coreCompleted){
            lblCoreReqValue.setText("Completed!");
            lblCoreReqValue.setForeground(new java.awt.Color(0, 128, 0)); //HL: color green for success 
        } else {
            lblCoreReqValue.setText("Incomplete.");
            lblCoreReqValue.setForeground(java.awt.Color.RED); //HL: color red for failure, notifies student that INFO5100 must be completed before graduating 
        }
        
        //HL: update Graduation Status in UI - Ensures 32 credit minimum has been met and INFO5100 (core requirement) was completed successfully 
        boolean readyToGraduate = (totalCredits >= REQUIRED_CREDITS) && coreCompleted;
        if (readyToGraduate){
            lblReadinessValue.setText("Qualified to Graduate!");
            lblReadinessValue.setForeground(new java.awt.Color(0, 128, 0)); //HL: color green for success 
            lblReadinessValue.setFont(new Font("Dialog", Font.BOLD, 16)); //HL: added import for font using AltEnter 
        } else {
            //HL: if not ready to graduate, display a reason why (either: not enough credits or core course requirement not finished 
            StringBuilder msg = new StringBuilder("Not Ready — ");
            if (totalCredits < REQUIRED_CREDITS){
                msg.append((REQUIRED_CREDITS - totalCredits)).append("additional credits required");
            }
            if (!coreCompleted){
                msg.append("Required core course INFO5100 is incomplete"); 
            }
            lblReadinessValue.setText(msg.toString());
            lblReadinessValue.setForeground(java.awt.Color.RED);
            lblReadinessValue.setFont(new Font("Dialog", Font.BOLD, 14));
            
        }
       
    }
}
