/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import university.CourseSchedule.CourseLoad;
import university.CourseSchedule.SeatAssignment;
import university.Persona.Transcript;

/**
 *
 * @author Hank_Local
 */
public class TranscriptJPanel extends javax.swing.JPanel {
    
    //HL: Business references 
    private Business business; //HL: added import using AltEnter
    private StudentProfile student; //HL: added import using AltEnter
    private JPanel CardSequencePanel; //HL: added import using AltEnter
    //HL: university reference to student profile to access transcripts 
    private university.Persona.StudentProfile uniStudentProfile;

    /**
     * Creates new form TranscriptJPanel
     */
    public TranscriptJPanel(Business b, StudentProfile spp, JPanel clp) {
        initComponents();
        business = b;
        student = spp;
        CardSequencePanel = clp;
        university.Department.Department dept = business.getDepartment();
        if (dept != null){
            uniStudentProfile = dept.getStudentDirectory().findStudent(student.getPerson().getPersonId()); //HL: gets university student profile 
        }
        
        //HL: ensures table is not editable 
        tblTranscript.setDefaultEditor(Object.class, null);
        loadPanel(); //HL: added method using AltEnter 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        comboSemester = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTranscript = new javax.swing.JTable();
        lblTuitionWarning = new javax.swing.JLabel();
        lblOverallGPA = new javax.swing.JLabel();
        lblOverallGPAValue = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("Student Transcript");

        lblSemester.setText("Semester");

        comboSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSemesterActionPerformed(evt);
            }
        });

        tblTranscript.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Term", "Standing", "Course ID", "Course Name", "Grade", "Term GPA", "Overall GPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTranscript);

        lblTuitionWarning.setText(" ");

        lblOverallGPA.setText("Overall GPA: ");

        lblOverallGPAValue.setText("--");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(285, 285, 285))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSemester)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblTuitionWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOverallGPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOverallGPAValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(comboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTuitionWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOverallGPA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOverallGPAValue)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        //HL: added by double clicking refresh button in UI
        loadPanel();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //HL: added by double clicking back button in UI
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel); //HL: added import using AltEnter 
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSemesterActionPerformed
        // TODO add your handling code here:
        //HL: added by double clicking comboSemester in UI
        String selected = (String) comboSemester.getSelectedItem();
        if (selected != null){
            loadTranscriptTable(selected);
        }
    }//GEN-LAST:event_comboSemesterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> comboSemester;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOverallGPA;
    private javax.swing.JLabel lblOverallGPAValue;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTuitionWarning;
    private javax.swing.JTable tblTranscript;
    // End of variables declaration//GEN-END:variables

    
    
    //HL: "Tuition Lock" method that checks if tuition is paid. only populates the semester combo box and the JTable if tuition was paid. Throws error to lblTutionWarning if not
    private void loadPanel() {
        if (uniStudentProfile == null) return;
        
        //HL: check to see if tuition is paid first, if not - student can't view their transcript until balance is paid 
        if (!uniStudentProfile.isTuitionPaid()){
            lblTuitionWarning.setText("Transcript locked. You must pay your balance before viewing.");
            tblTranscript.setVisible(false);
            comboSemester.setEnabled(false); 
            lblOverallGPAValue.setText("--");
            return; 
        }
        //HL: if tuition is paid, transcript unlocks 
        lblTuitionWarning.setText(" ");
        tblTranscript.setVisible(true);
        comboSemester.setEnabled(true);
        
        populateSemesterDropdown(); //HL: added method using AltEnter
        updateOverallGPA(); //HL: added method using AltEnter
    }

    
    //HL: method that refers to student's transcript history, then enables the semester combo box with "all semesters" as first option so student can view all courses they've taken w/ details
    private void populateSemesterDropdown() {
        comboSemester.removeAllItems();
        comboSemester.addItem("All Semesters"); //HL: first option in comboSemester so students can see full history 
        
        Transcript transcript = uniStudentProfile.getTranscript(); //HL: added import using AltEnter
        ArrayList<String> semesters = transcript.getSemesters(); //HL: added import using AltEnter
        
        for (String sem : semesters){
            comboSemester.addItem(sem); 
        }
        
        //HL: load full list of courses for a student in JTable by default
        loadTranscriptTable("All Semesters"); //HL: added method using AltEnter
        
    }

    
    //HL: updates lblOverallGPA 
    private void updateOverallGPA() {
        if (uniStudentProfile == null) return;
        double gpa = uniStudentProfile.getTranscript().getOverallGPA();
        lblOverallGPAValue.setText(String.format("%.2f", gpa));
        
    }

    
    //HL: method that filters the JTable based on combo box selextion "All Semesters" or specific semester selection (ex Fall 2025) 
    private void loadTranscriptTable(String selectedSemester) {
        DefaultTableModel model = (DefaultTableModel) tblTranscript.getModel(); //HL: added import using AltEnter
        model.setRowCount(0); //HL: clears rows 
        
        if (uniStudentProfile == null) return; 
        
        Transcript transcript = uniStudentProfile.getTranscript();
        
        if (selectedSemester.equals("All Semesters")){
            //HL: load full list of courses for a student from all semesters in JTable when All Semesters is selected
            for (String sem : transcript.getSemesters()){
                addSemesterRowsToTable(transcript, sem, model); //HL: added method using AltEnter
            }
            
        } else {
            //HL: only show the students courses from the selected semester (ex. Fall 2025)
            addSemesterRowsToTable(transcript, selectedSemester, model);
        }
        
        
    }

    
    //HL: helper method that adds rows to JTable for all courses from one single semester (pulled from student's SeatAssignment) 
    private void addSemesterRowsToTable(Transcript transcript, String semester, DefaultTableModel model) {
        CourseLoad cl = transcript.getCourseLoadBySemester(semester); //HL: added import using AltEnter
        if (cl == null) return;
        
        double termGPA    = transcript.getSemesterGPA(semester);
        double overallGPA = transcript.getOverallGPA();
        String standing   = transcript.getAcademicStanding(semester);
        
        for (SeatAssignment sa : cl.getSeatAssignments()){ //HL: added import using AltEnter
            String courseId = sa.getAssociatedCourse().getCOurseNumber();
            String courseName = sa.getAssociatedCourse().getName();
            String grade = sa.getGrade(); //HL: N/A if not graded
            
            model.addRow(new Object[]{
                semester, //HL: Term column in JTable
                standing, //HL: Standing column in JTable (Academic Standing)
                courseId, //HL: Course ID column in JTable
                courseName, //HL: Course Name column in JTable
                grade, //HL: Grade column in JTable
                String.format("%.2f", termGPA), //HL: Term GPA column in JTable 
                String.format("%.2f", overallGPA) //HL: Overall GPA column in JTable 
            });
            
        }    
    }
}
