/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import university.Department.Department;
import university.Persona.TuitionRecord;

/**
 *
 * @author Hank_Local
 */
public class TuitionPaymentJPanel extends javax.swing.JPanel {
    
    //HL: business references 
    private Business business; //HL: added import using AltEnter
    private StudentProfile student;  //HL: added import using AltEnter
    private JPanel CardSequencePanel; //HL: added import using AltEnter
    //HL: university refrence to student profile for tuition balance & access to payments 
    private university.Persona.StudentProfile uniStudentProfile; 

    /**
     * Creates new form TuitionPaymentJPanel
     */
    public TuitionPaymentJPanel(Business b, StudentProfile spp, JPanel clp) {
        initComponents();
        business = b;
        student = spp;
        CardSequencePanel = clp;
        
        //HL: get university student profile 
        Department dept = business.getDepartment(); //HL: added import using AltEnter
        if (dept != null){
            uniStudentProfile = dept.getStudentDirectory().findStudent(student.getPerson().getPersonId()); 
        }
        
        //HL: ensure payment history is not-editable in JTable 
        tblPaymentHistory.setDefaultEditor(Object.class, null);
        tblPaymentHistory.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); //HL: added import using Alt Enter

        initializeBalance(); //HL: created method using AltEnter
        loadPanel(); //HL: created method using AltEnter
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblBalanceValue = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaymentHistory = new javax.swing.JTable();
        btnPayTuition = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("Make a Tuition Payment");

        lblBalance.setText("Current Balance: ");

        lblBalanceValue.setText("--");

        lblStatus.setText(" ");

        tblPaymentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Payment Date", "Amount", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPaymentHistory);

        btnPayTuition.setText("Pay Tuition");
        btnPayTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayTuitionActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPayTuition)
                        .addGap(104, 104, 104))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBalance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBalanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalance)
                    .addComponent(lblBalanceValue)
                    .addComponent(lblStatus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPayTuition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayTuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayTuitionActionPerformed
        // TODO add your handling code here:
        //HL: added by double-click button in UI 
        payTuition();
        
    }//GEN-LAST:event_btnPayTuitionActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //HL: added by double-click button in UI 
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel); //HL: added import using AltEnter 
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPayTuition;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalanceValue;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblPaymentHistory;
    // End of variables declaration//GEN-END:variables

    
    //HL: method to create the initial balance based on tuition owed for a student profile 
    //HL: prevents accidentally resetting a student's tuition balance back to the full amount every time they open the panel after paying 
    private void initializeBalance() {
        if (uniStudentProfile == null) return; 
        double currentBalance = uniStudentProfile.getBalance();
        
        //HL: if not initialized, calculate & set balance 
        if (currentBalance == 0.0){
            double totalOwed = uniStudentProfile.getTotalTuitionOwed();
            uniStudentProfile.setBalance(totalOwed);
        }
        
    }

    
    //HL: method that loads panel & updates lblBalance in UI 
    //HL: populates all payment history for the student in the JTable 
    private void loadPanel() {
        if (uniStudentProfile == null) return;

        updateBalanceLabel(); //HL: added method using AltEnter
        loadPaymentHistory(); //HL: added method using AltEnter
        
        
    }

    
    //HL: method that  populates the total balance with current amount owed/paid 
    private void updateBalanceLabel() {
        double balance = uniStudentProfile.getBalance();
        if (balance <= 0){
            lblBalanceValue.setText("$0.00 - Fully Paid!");
            lblBalanceValue.setForeground(new java.awt.Color(0, 128, 0)); //HL: green for paid status 
        } else { 
            lblBalanceValue.setText("$" + String.format("%.2f", balance));
            lblBalanceValue.setForeground(java.awt.Color.RED); //HL: red for outstanding balance 
        }
        
        
    }

    
    //HL: method that reviews student's payment history & displays (pulled from TuitionRecord.java) 
    private void loadPaymentHistory() {
        DefaultTableModel model = (DefaultTableModel) tblPaymentHistory.getModel(); //HL: added import using AltEnter 
        model.setRowCount(0); //HL: clears rows 
        
        List<TuitionRecord> history = uniStudentProfile.getPaymentHistory(); //HL: added 2 imports using AltEnter (TuitionRecord & List) 
        
        //HL: no payements yet, possibly brand new student 
        if (history.isEmpty()){
            lblStatus.setForeground(java.awt.Color.GRAY);
            lblStatus.setText("No payments yet.");
            return;
        }
        //adds data for payment date, amount, and description in a JTable row 
        for (TuitionRecord record : history){
            model.addRow(new Object[]{
                record.getDate(),
                record.getFormattedAmount(),
                record.getDescription()
            }); 
        }
        lblStatus.setText(" ");
        
    }
    
    //HL: method to process a tuition payment 
    //HL: per instructions if Balance <= 0 create a dialog box informing student that theres no balance, do not record as an action in payment history
    //HL: if the student has a balance, pay & record transaction 
    private void payTuition(){
        if (uniStudentProfile == null) return;
        double balance = uniStudentProfile.getBalance();
        
        //HL: dialog displayed to show student they do not have a balance - do not record this into payment history 
        if (balance <= 0){
            JOptionPane.showMessageDialog(this, "No balance.", "Payment Info", JOptionPane.INFORMATION_MESSAGE); //HL: added import using AltEnter
            return; 
        }
        
        //HL: yes/no payment confirmation for student prior to processing 
        int confirm = JOptionPane.showConfirmDialog(this, "Pay balalnce of $" + String.format("%.2f", balance) + "?", "Confirm Payment", JOptionPane.YES_NO_OPTION); 
        if (confirm != JOptionPane.YES_OPTION) return;
        
        //HL: process payment & pay() subtracts the paid balance and records the payment in TuitionRecord
        uniStudentProfile.pay(balance);
        lblStatus.setForeground(new java.awt.Color(0, 128, 0)); //HL: green for successful payment 
        lblStatus.setText("Payment of $" + String.format("%.2f", balance) + " successfully processed.");
        
        //HL: refresh 
        updateBalanceLabel();
        loadPaymentHistory();
        
    }
    
}
