/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.Business;
import Business.Profiles.RegistrarProfile;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import university.CourseSchedule.CourseLoad;
import university.CourseSchedule.SeatAssignment;
import university.Department.Department;

/**
 *
 * @author Lanre
 */
public class TuitionAndFinancialJPanel extends javax.swing.JPanel {
    Business business;
    RegistrarProfile registrar;
    JPanel CardSequencePanel;
    /**
     * Creates new form TuitionAndFinancialJPanel
     */
    public TuitionAndFinancialJPanel(Business business, RegistrarProfile registrar, JPanel CardSequencePanel) {
        initComponents();
        
        txtReportOutput.setEditable(false);
        txtReportOutput.setLineWrap(true);
        txtReportOutput.setWrapStyleWord(true);
        
        this.business = business;
        this.registrar = registrar;
        this.CardSequencePanel = CardSequencePanel;
        
        populateDepartments();
        populateSemesters();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();
        lblSemester = new javax.swing.JLabel();
        cmbSemester = new javax.swing.JComboBox<>();
        btnLoad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTuitionAndFinancial = new javax.swing.JTable();
        lblFinancialReport = new javax.swing.JLabel();
        btnTotalCollected = new javax.swing.JButton();
        btnUnpaidSummary = new javax.swing.JButton();
        btnDeptBreakdown = new javax.swing.JButton();
        spReportOutput = new javax.swing.JScrollPane();
        txtReportOutput = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("Tuition And Finacial Reconciliation");

        lblDepartment.setText("Department");

        lblSemester.setText("Semester");

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        tblTuitionAndFinancial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Total Due", "Paid", "Balance", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTuitionAndFinancial);

        lblFinancialReport.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFinancialReport.setText("Financial Report");

        btnTotalCollected.setText("Total Collected");
        btnTotalCollected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalCollectedActionPerformed(evt);
            }
        });

        btnUnpaidSummary.setText("Unpaid Summary");
        btnUnpaidSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnpaidSummaryActionPerformed(evt);
            }
        });

        btnDeptBreakdown.setText("Department Breakdown");
        btnDeptBreakdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeptBreakdownActionPerformed(evt);
            }
        });

        txtReportOutput.setColumns(20);
        txtReportOutput.setRows(5);
        spReportOutput.setViewportView(txtReportOutput);

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFinancialReport)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTotalCollected))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnUnpaidSummary)
                                        .addGap(82, 82, 82)
                                        .addComponent(btnDeptBreakdown))
                                    .addComponent(spReportOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDepartment)
                                .addGap(23, 23, 23)
                                .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(lblSemester)
                                .addGap(18, 18, 18)
                                .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 63, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDepartment)
                            .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSemester)
                            .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLoad))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFinancialReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTotalCollected)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnUnpaidSummary)
                                .addComponent(btnDeptBreakdown)))
                        .addGap(18, 18, 18)
                        .addComponent(spReportOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:       
        String selectedSemester = (String) cmbSemester.getSelectedItem();      
        String selectedDept = (String) cmbDepartment.getSelectedItem();

        DefaultTableModel model = (DefaultTableModel) tblTuitionAndFinancial.getModel();
        model.setRowCount(0); // clear table

        double totalCollected = 0.0;
        double totalUnpaid = 0.0;

        for (StudentProfile sp : business.getStudentDirectory().getStudentList()) {

            university.Persona.StudentProfile up = sp.getUniversityProfile();
           
            if (up == null) {
                continue;
            }

            CourseLoad cl = up.getCourseLoadBySemester(selectedSemester);
            if (cl == null) {
                continue;
            }
                    
            double due = 0.0;

            for (SeatAssignment sa : cl.getSeatAssignments()) {
                if (sa == null || sa.getAssociatedCourse() == null) {
                    continue;
                }
                due += sa.getAssociatedCourse().getCoursePrice();
            }

            if (due <= 0) {
                continue;
            }

            double balance = up.getBalance();
            double paid = due - balance;

            if (paid < 0) {
                paid = 0;
            }
            if (paid > due) {
                paid = due;
            }

            String status = getStatus(due, balance);

            totalCollected += paid;
            if (balance > 0) {
                totalUnpaid += balance;
            }

            model.addRow(new Object[]{
                sp.getPerson().getPersonId(),
                sp.getPerson().getFullname(),
                String.format("%.2f", due),
                String.format("%.2f", paid),
                String.format("%.2f", balance),
                status
            });
        }

    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnTotalCollectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalCollectedActionPerformed
        // TODO add your handling code here:
        String selectedSemester = (String) cmbSemester.getSelectedItem();
        double totalCollected = 0.0;

        for (StudentProfile sp : business.getStudentDirectory().getStudentList()) {

            university.Persona.StudentProfile up = sp.getUniversityProfile();
            if (up == null) {
                continue;
            }

            CourseLoad cl = up.getCourseLoadBySemester(selectedSemester);
            if (cl == null) {
                continue;
            }

            double due = 0.0;
            for (SeatAssignment sa : cl.getSeatAssignments()) {
                due += sa.getAssociatedCourse().getCoursePrice();
            }

            double balance = up.getBalance();
            double paid = Math.max(0, due - balance);

            totalCollected += paid;
        }

        txtReportOutput.setText(
                "Total Tuition Collected for " + selectedSemester
                + "\n\n$" + String.format("%.2f", totalCollected)
        );
    }//GEN-LAST:event_btnTotalCollectedActionPerformed

    private void btnUnpaidSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnpaidSummaryActionPerformed
        // TODO add your handling code here:
        String selectedSemester = (String) cmbSemester.getSelectedItem();
        double totalUnpaid = 0.0;
        int unpaidStudents = 0;

        for (StudentProfile sp : business.getStudentDirectory().getStudentList()) {

            university.Persona.StudentProfile up = sp.getUniversityProfile();
            if (up == null) {
                continue;
            }

            CourseLoad cl = up.getCourseLoadBySemester(selectedSemester);
            if (cl == null) {
                continue;
            }

            double balance = up.getBalance();

            if (balance > 0) {
                totalUnpaid += balance;
                unpaidStudents++;
            }
        }

        txtReportOutput.setText(
                "Unpaid Tuition Summary for " + selectedSemester
                + "\n\nStudents with Outstanding Balance: " + unpaidStudents
                + "\nTotal Outstanding Amount: $" + String.format("%.2f", totalUnpaid)
        );
    }//GEN-LAST:event_btnUnpaidSummaryActionPerformed

    private void btnDeptBreakdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeptBreakdownActionPerformed
        // TODO add your handling code here:
        String selectedSemester = (String) cmbSemester.getSelectedItem();
        String selectedDept = (String) cmbDepartment.getSelectedItem();

        double departmentRevenue = 0.0;

        for (StudentProfile sp : business.getStudentDirectory().getStudentList()) {

            university.Persona.StudentProfile up = sp.getUniversityProfile();
            if (up == null) {
                continue;
            }

            CourseLoad cl = up.getCourseLoadBySemester(selectedSemester);
            if (cl == null) {
                continue;
            }

            for (SeatAssignment sa : cl.getSeatAssignments()) {

                if (!"All".equals(selectedDept)) {
                    // If your Course has department info, filter here
                    // Otherwise skip filtering for now
                }

                departmentRevenue += sa.getAssociatedCourse().getCoursePrice();
            }
        }

        txtReportOutput.setText(
                "Department Revenue Breakdown (" + selectedDept + ")"
                + "\n\nTotal Revenue: $" + String.format("%.2f", departmentRevenue)
        );
    }//GEN-LAST:event_btnDeptBreakdownActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeptBreakdown;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnTotalCollected;
    private javax.swing.JButton btnUnpaidSummary;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblFinancialReport;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane spReportOutput;
    private javax.swing.JTable tblTuitionAndFinancial;
    private javax.swing.JTextArea txtReportOutput;
    // End of variables declaration//GEN-END:variables

    private void populateDepartments() {
        cmbDepartment.removeAllItems();
        cmbDepartment.addItem("All");  // allow viewing all departments

        for (Department d : business.getDepartments()) {
            cmbDepartment.addItem(d.toString());
        }
    }

    private void populateSemesters() {
        cmbSemester.removeAllItems();
        cmbSemester.addItem("Fall 2026");
        cmbSemester.addItem("Spring 2027");
        cmbSemester.addItem("Fall 2027");
    }
    
    private String getStatus(double due, double balance) {
        if (due <= 0) {
            return "N/A";
        }
        if (balance <= 0) {
            return "Paid";
        }
        if (balance >= due) {
            return "Unpaid";
        }
        return "Partial";
    }
}
