/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

/**
 *
 * @author emmanuelcroll
 */
public class CoursePerformanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CoursePerformanceJPanel
     */
     public CoursePerformanceJPanel() {
        initComponents();
        populateDropdowns();
    }
      private void populateDropdowns() {
        cmbSelectCourse.removeAllItems();
        cmbSelectCourse.addItem("INFO 5100 - Application Engineering");
        cmbSelectCourse.addItem("INFO 6150 - Web Design");
        
        cmbSemester.removeAllItems();
        cmbSemester.addItem("Fall 2024");
        cmbSemester.addItem("Spring 2024");
        cmbSemester.addItem("Fall 2023");
        
        cmbSelectCourse.addActionListener(e -> loadPerformanceData());
        cmbSemester.addActionListener(e -> loadPerformanceData());
        
        loadPerformanceData();
    }
    
    private void loadPerformanceData() {
        lblAverageGradeValue.setText("3.45");
        lblEnrollmentValue.setText("18 students");
        lblClassGPAValue.setText("B+");
        
        String[][] distributionData = {
            {"A", "5", "28%"},
            {"A-", "2", "11%"},
            {"B+", "4", "22%"},
            {"B", "5", "28%"},
            {"B-", "1", "6%"},
            {"C+", "1", "6%"}
        };
        
        String[] columnNames = {"Grade", "Count", "Percentage"};
        
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(distributionData, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tblGradeDistribution.setModel(model);
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSelectCourse = new javax.swing.JLabel();
        lblAverageGrade = new javax.swing.JLabel();
        lblGradeDistribution = new javax.swing.JLabel();
        cmbSelectCourse = new javax.swing.JComboBox<>();
        lblSemester = new javax.swing.JLabel();
        cmbSemester = new javax.swing.JComboBox<>();
        lblAverageGradeValue = new javax.swing.JLabel();
        lblEnrollment = new javax.swing.JLabel();
        lblEnrollmentValue = new javax.swing.JLabel();
        lblClassGPA = new javax.swing.JLabel();
        lblClassGPAValue = new javax.swing.JLabel();
        distributionScrollPane = new javax.swing.JScrollPane();
        tblGradeDistribution = new javax.swing.JTable();
        btnExport = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Course Performance Report");

        lblSelectCourse.setText("Select Course:");

        lblAverageGrade.setText("Average Grade:");

        lblGradeDistribution.setText("Grade Distribution:");

        cmbSelectCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectCourseActionPerformed(evt);
            }
        });

        lblSemester.setText("Semester:");

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSemesterActionPerformed(evt);
            }
        });

        lblAverageGradeValue.setText("jLabel6");

        lblEnrollment.setText("Enrollment:");

        lblEnrollmentValue.setText("jLabel8");

        lblClassGPA.setText("Class GPA:");

        lblClassGPAValue.setText("jLabel10");

        tblGradeDistribution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Grade", "Count", "Percentage "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        distributionScrollPane.setViewportView(tblGradeDistribution);

        btnExport.setText("Export Report");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(distributionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGradeDistribution)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAverageGrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAverageGradeValue)
                        .addGap(33, 33, 33)
                        .addComponent(lblEnrollment)
                        .addGap(18, 18, 18)
                        .addComponent(lblEnrollmentValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblClassGPA)
                        .addGap(27, 27, 27)
                        .addComponent(lblClassGPAValue))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSelectCourse)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblSemester)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExport)
                        .addGap(268, 268, 268))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCourse)
                    .addComponent(cmbSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemester)
                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAverageGrade)
                    .addComponent(lblAverageGradeValue)
                    .addComponent(lblEnrollment)
                    .addComponent(lblEnrollmentValue)
                    .addComponent(lblClassGPA)
                    .addComponent(lblClassGPAValue))
                .addGap(49, 49, 49)
                .addComponent(lblGradeDistribution)
                .addGap(32, 32, 32)
                .addComponent(distributionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExport)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this,
            "Report exported successfully!",
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExportActionPerformed

    private void cmbSelectCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectCourseActionPerformed
        // TODO add your handling code here:
            loadPerformanceData();

    }//GEN-LAST:event_cmbSelectCourseActionPerformed

    private void cmbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemesterActionPerformed
        // TODO add your handling code here:
            loadPerformanceData();

    }//GEN-LAST:event_cmbSemesterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JComboBox<String> cmbSelectCourse;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JScrollPane distributionScrollPane;
    private javax.swing.JLabel lblAverageGrade;
    private javax.swing.JLabel lblAverageGradeValue;
    private javax.swing.JLabel lblClassGPA;
    private javax.swing.JLabel lblClassGPAValue;
    private javax.swing.JLabel lblEnrollment;
    private javax.swing.JLabel lblEnrollmentValue;
    private javax.swing.JLabel lblGradeDistribution;
    private javax.swing.JLabel lblSelectCourse;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblGradeDistribution;
    // End of variables declaration//GEN-END:variables
}
