/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import Business.Business;
import Business.Profiles.StudentProfile;


/**
 *
 * @author emmanuelcroll
 */
public class GradeAssignmentsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GradeAssignmentsJPanel
     */
    
    Business business;
    javax.swing.JPanel CardSequencePanel;
    
    
    public GradeAssignmentsJPanel(Business b, javax.swing.JPanel clp) {
        business = b;
        CardSequencePanel = clp;
        initComponents();
        populateCourseDropdown();
        populateGradeDropdown();
    }
    
    private void populateCourseDropdown() {
    cmbSelectCourse.removeAllItems();
    university.CourseSchedule.CourseSchedule cs =
        business.getDepartment().getCourseSchedule("Fall 2025");
    if (cs != null) {
        for (university.CourseSchedule.CourseOffer co : cs.getSchedule()) {
            cmbSelectCourse.addItem(co.getCourseNumber() + " - " +
                co.getSubjectCourse().getName());
        }
    }
    cmbSelectCourse.addActionListener(e -> loadStudents());
    loadStudents();
}
    
    private void populateGradeDropdown() {
        cmbAssignGrade.removeAllItems();
        cmbAssignGrade.addItem("A");
        cmbAssignGrade.addItem("A-");
        cmbAssignGrade.addItem("B+");
        cmbAssignGrade.addItem("B");
        cmbAssignGrade.addItem("B-");
        cmbAssignGrade.addItem("C+");
        cmbAssignGrade.addItem("C");
        cmbAssignGrade.addItem("C-");
        cmbAssignGrade.addItem("F");
    }
    
    private void loadStudents() {
    String selected = (String) cmbSelectCourse.getSelectedItem();
    if (selected == null) return;
    String courseNum = selected.split(" - ")[0].trim();

    java.util.ArrayList<String[]> rows = new java.util.ArrayList<>();
    for (StudentProfile bsp : business.getStudentDirectory().getStudentList()) {
        university.Persona.StudentProfile usp = bsp.getUniversityProfile();
        if (usp == null) continue;
        for (university.CourseSchedule.SeatAssignment sa : usp.getCourseList()) {
            if (sa.getCourseOffer().getCourseNumber().equals(courseNum)) {
                rows.add(new String[]{
                    bsp.getPerson().getPersonId(),
                    bsp.getPerson().getFullname(),
                    sa.getGrade()
                });
            }
        }
    }
    String[][] data = rows.toArray(new String[0][]);
    String[] cols = {"Student ID", "Name", "Current Grade"};
    javax.swing.table.DefaultTableModel model =
        new javax.swing.table.DefaultTableModel(data, cols) {
            @Override
            public boolean isCellEditable(int r, int c) { return false; }
        };
    tblStudentsGrade.setModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentsGradeScrollPane = new javax.swing.JScrollPane();
        tblStudentsGrade = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblSelectCourse = new javax.swing.JLabel();
        cmbSelectCourse = new javax.swing.JComboBox<>();
        lblAssignGrade = new javax.swing.JLabel();
        cmbAssignGrade = new javax.swing.JComboBox<>();
        btnAssignToSelected = new javax.swing.JButton();

        tblStudentsGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Current Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentsGradeScrollPane.setViewportView(tblStudentsGrade);

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Grade Assignments");

        lblSelectCourse.setText("Select Course:");

        cmbSelectCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectCourseActionPerformed(evt);
            }
        });

        lblAssignGrade.setText("Assign Grade:");

        cmbAssignGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAssignToSelected.setText("Assign to Selected");
        btnAssignToSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lblSelectCourse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(studentsGradeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lblAssignGrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAssignGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnAssignToSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCourse)
                    .addComponent(cmbSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(studentsGradeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssignGrade)
                    .addComponent(cmbAssignGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignToSelected))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToSelectedActionPerformed
        // TODO add your handling code here:
        String selectedStudent = (String) cmbSelectCourse.getSelectedItem();
    String grade = (String) cmbAssignGrade.getSelectedItem();
    if (selectedStudent == null || grade == null) return;

    String studentId = selectedStudent.replaceAll(".*\\((.*)\\)", "$1").trim();
    String selectedCourse = (String) cmbSelectCourse.getSelectedItem();
    if (selectedCourse == null) return;
    String courseNum = selectedCourse.split(" - ")[0].trim();

    StudentProfile bsp = business.getStudentDirectory().findStudentbyID(studentId);
    if (bsp == null || bsp.getUniversityProfile() == null) return;

    for (university.CourseSchedule.SeatAssignment sa :
            bsp.getUniversityProfile().getCourseList()) {
        if (sa.getCourseOffer().getCourseNumber().equals(courseNum)) {
            sa.setGrade(grade);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Grade " + grade + " assigned to " + bsp.getPerson().getFullname(),
                "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            loadStudents(); // refresh table
            return;
        }
    }

    }//GEN-LAST:event_btnAssignToSelectedActionPerformed

    private void cmbSelectCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectCourseActionPerformed
        // TODO add your handling code here:
        loadStudents();

    }//GEN-LAST:event_cmbSelectCourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToSelected;
    private javax.swing.JComboBox<String> cmbAssignGrade;
    private javax.swing.JComboBox<String> cmbSelectCourse;
    private javax.swing.JLabel lblAssignGrade;
    private javax.swing.JLabel lblSelectCourse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane studentsGradeScrollPane;
    private javax.swing.JTable tblStudentsGrade;
    // End of variables declaration//GEN-END:variables
}
