/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

/**
 *
 * @author emmanuelcroll
 */
public class GradeAssignmentsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GradeAssignmentsJPanel
     */
    public GradeAssignmentsJPanel() {
        initComponents();
        populateCourseDropdown();
        populateGradeDropdown();
    }
    
    private void populateCourseDropdown() {
        cmbSelectStudents.removeAllItems();
        cmbSelectStudents.addItem("INFO 5100 - Application Engineering");
        cmbSelectStudents.addItem("INFO 6150 - Web Design");
        
        cmbSelectStudents.addActionListener(e -> loadStudents());
        loadStudents();
    }
    
    private void populateGradeDropdown() {
        cmbAssignGrade.removeAllItems();
        cmbAssignGrade.addItem("A");
        cmbAssignGrade.addItem("A-");
        cmbAssignGrade.addItem("B+");
        cmbAssignGrade.addItem("B");
        cmbAssignGrade.addItem("B-");
        cmbAssignGrade.addItem("C+");
        cmbAssignGrade.addItem("C");
        cmbAssignGrade.addItem("C-");
        cmbAssignGrade.addItem("F");
    }
    
    private void loadStudents() {
        String[][] mockStudents = {
            {"S001", "Alex Thompson", "A"},
            {"S002", "Emma Williams", "B+"},
            {"S003", "Noah Lee", "A-"},
            {"S004", "Olivia Harris", "B"},
            {"S005", "Liam Clark", "Not Graded"}
        };
        
        String[] columnNames = {"Student ID", "Name", "Current Grade"};
        
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(mockStudents, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tblStudentsGrade.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentsGradeScrollPane = new javax.swing.JScrollPane();
        tblStudentsGrade = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblSelectCourse = new javax.swing.JLabel();
        cmbSelectStudents = new javax.swing.JComboBox<>();
        lblAssignGrade = new javax.swing.JLabel();
        cmbAssignGrade = new javax.swing.JComboBox<>();
        btnAssignToSelected = new javax.swing.JButton();

        tblStudentsGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Current Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentsGradeScrollPane.setViewportView(tblStudentsGrade);

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Grade Assignments");

        lblSelectCourse.setText("Select Course:");

        cmbSelectStudents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectStudentsActionPerformed(evt);
            }
        });

        lblAssignGrade.setText("Assign Grade:");

        cmbAssignGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAssignToSelected.setText("Assign to Selected");
        btnAssignToSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lblSelectCourse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbSelectStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(studentsGradeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lblAssignGrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAssignGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnAssignToSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCourse)
                    .addComponent(cmbSelectStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(studentsGradeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssignGrade)
                    .addComponent(cmbAssignGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignToSelected))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToSelectedActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStudentsGrade.getSelectedRow();
        
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a student from the table",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String selectedGrade = (String) cmbAssignGrade.getSelectedItem();
        if (selectedGrade == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a grade",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String studentName = (String) tblStudentsGrade.getValueAt(selectedRow, 1);
        tblStudentsGrade.setValueAt(selectedGrade, selectedRow, 2);
        
        javax.swing.JOptionPane.showMessageDialog(this,
            "Grade " + selectedGrade + " assigned to " + studentName,
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAssignToSelectedActionPerformed

    private void cmbSelectStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectStudentsActionPerformed
        // TODO add your handling code here:
        loadStudents();

    }//GEN-LAST:event_cmbSelectStudentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToSelected;
    private javax.swing.JComboBox<String> cmbAssignGrade;
    private javax.swing.JComboBox<String> cmbSelectStudents;
    private javax.swing.JLabel lblAssignGrade;
    private javax.swing.JLabel lblSelectCourse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane studentsGradeScrollPane;
    private javax.swing.JTable tblStudentsGrade;
    // End of variables declaration//GEN-END:variables
}
