/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

/**
 *
 * @author emmanuelcroll
 */
public class ManageEnrollmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnrollmentJPanel
     */
    public ManageEnrollmentJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSelectCourses = new javax.swing.JLabel();
        lblCurrentSyllabus = new javax.swing.JLabel();
        btnOpenEnrollment = new javax.swing.JButton();
        cmbSelectCourses = new javax.swing.JComboBox<>();
        lblCurrentSyllabusStatus = new javax.swing.JLabel();
        btnCloseEnrollment = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Manage Course Enrollment ");

        lblSelectCourses.setText("Select Courses");

        lblCurrentSyllabus.setText("Enrollment Status");

        btnOpenEnrollment.setText("Open Enrollment");

        cmbSelectCourses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCurrentSyllabusStatus.setText("Open");

        btnCloseEnrollment.setText("Close Enrollment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCurrentSyllabus)
                            .addComponent(lblSelectCourses))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSelectCourses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCurrentSyllabusStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpenEnrollment)
                        .addGap(18, 18, 18)
                        .addComponent(btnCloseEnrollment)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitle)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCourses)
                    .addComponent(cmbSelectCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentSyllabus)
                    .addComponent(lblCurrentSyllabusStatus))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenEnrollment)
                    .addComponent(btnCloseEnrollment))
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseEnrollment;
    private javax.swing.JButton btnOpenEnrollment;
    private javax.swing.JComboBox<String> cmbSelectCourses;
    private javax.swing.JLabel lblCurrentSyllabus;
    private javax.swing.JLabel lblCurrentSyllabusStatus;
    private javax.swing.JLabel lblSelectCourses;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
