/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import Business.Business;


/**
 *
 * @author emmanuelcroll
 */
public class ManageSyllabusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSyllabusJPanel
     * 
     */
    
    Business business;
    javax.swing.JPanel CardSequencePanel;
    
    public ManageSyllabusJPanel(Business b, javax.swing.JPanel clp) {
        business = b;
        CardSequencePanel = clp;
        initComponents();
        populateCourseDropdown();
    }

    
     private void populateCourseDropdown() {
    cmbSelectCourses.removeAllItems();
    university.CourseSchedule.CourseSchedule cs =
        business.getDepartment().getCourseSchedule("Fall 2025");
    if (cs != null) {
        for (university.CourseSchedule.CourseOffer co : cs.getSchedule()) {
            cmbSelectCourses.addItem(co.getCourseNumber() + " - " +
                co.getSubjectCourse().getName());
        }
    }
    lblCurrentSyllabusStatus.setText("No syllabus uploaded");
}
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUploadSyllabus = new javax.swing.JButton();
        cmbSelectCourses = new javax.swing.JComboBox<>();
        fieldSyllabusURL = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblSelectCourses = new javax.swing.JLabel();
        lblCurrentSyllabus = new javax.swing.JLabel();
        lblSyllabusURL = new javax.swing.JLabel();
        lblCurrentSyllabusStatus = new javax.swing.JLabel();

        btnUploadSyllabus.setText("Upload Syllabus");
        btnUploadSyllabus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadSyllabusActionPerformed(evt);
            }
        });

        cmbSelectCourses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectCoursesActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Manage Course Syllabus");

        lblSelectCourses.setText("Select Courses");

        lblCurrentSyllabus.setText("Current Syllabus");

        lblSyllabusURL.setText("Syllabus URL");

        lblCurrentSyllabusStatus.setText("No Syllabus Uploaded");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(220, 220, 220))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCurrentSyllabus)
                            .addComponent(lblSelectCourses)
                            .addComponent(lblSyllabusURL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldSyllabusURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSelectCourses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCurrentSyllabusStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btnUploadSyllabus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblTitle)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCourses)
                    .addComponent(cmbSelectCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentSyllabus)
                    .addComponent(lblCurrentSyllabusStatus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSyllabusURL)
                    .addComponent(fieldSyllabusURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnUploadSyllabus)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadSyllabusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadSyllabusActionPerformed
        // TODO add your handling code here:
        String url = fieldSyllabusURL.getText();
        
        if (url == null || url.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter a syllabus URL",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        lblCurrentSyllabusStatus.setText("Syllabus: " + url);
        
        javax.swing.JOptionPane.showMessageDialog(this,
            "Syllabus uploaded successfully!",
            "Success",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        fieldSyllabusURL.setText("");
    }//GEN-LAST:event_btnUploadSyllabusActionPerformed

    private void cmbSelectCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelectCoursesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUploadSyllabus;
    private javax.swing.JComboBox<String> cmbSelectCourses;
    private javax.swing.JTextField fieldSyllabusURL;
    private javax.swing.JLabel lblCurrentSyllabus;
    private javax.swing.JLabel lblCurrentSyllabusStatus;
    private javax.swing.JLabel lblSelectCourses;
    private javax.swing.JLabel lblSyllabusURL;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
