/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole; 
import Business.Business;
import Business.Profiles.StudentProfile;

/**
 *
 * @author emmanuelcroll
 */
public class StudentProgressReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentProgressReportJPanel
     */
    Business business;
    javax.swing.JPanel CardSequencePanel;
    
    public StudentProgressReportJPanel(Business b, javax.swing.JPanel clp) {
        business = b;
        CardSequencePanel = clp;
        initComponents();
        populateStudentDropdown();
    }

    
    
    private void populateStudentDropdown() {
        cmbSelectStudents.removeAllItems();
        for (StudentProfile sp :
                business.getStudentDirectory().getStudentList()) {
            cmbSelectStudents.addItem(sp.getPerson().getFullname() +
                " (" + sp.getPerson().getPersonId() + ")");
        }
        loadStudentProgress();
    }

private void loadStudentProgress() {
        String selected = (String) cmbSelectStudents.getSelectedItem();
        if (selected == null) return;
        String id = selected.replaceAll(".*\\((.*)\\)", "$1").trim();
        StudentProfile bsp =
            business.getStudentDirectory().findStudentbyID(id);
        if (bsp == null) return;
        university.Persona.StudentProfile usp = bsp.getUniversityProfile();
        if (usp == null) return;

        lblNameValue.setText(bsp.getPerson().getFullname());
        lblStudentIDValue.setText(bsp.getPerson().getPersonId());
        lblEmailValue.setText(bsp.getPerson().getPersonId() + "@northeastern.edu");

        java.util.ArrayList<university.CourseSchedule.SeatAssignment> courses =
            usp.getCourseList();
        lblCourseValue.setText(courses.isEmpty() ? "None" :
            courses.get(0).getCourseOffer().getCourseNumber());

        double gpa = usp.getTranscript().getOverallGPA();
        lblCurrentGradeValue.setText(String.format("%.2f GPA", gpa));
        lblAssignmentsValue.setText(courses.size() + " courses enrolled");
        lblAttendanceValue.setText(usp.getTranscript().getAcademicStanding("Fall 2025"));
    

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSelectStudents = new javax.swing.JLabel();
        cmbSelectStudents = new javax.swing.JComboBox<>();
        lblNameLabel = new javax.swing.JLabel();
        lblStudentIDLabel = new javax.swing.JLabel();
        lblEmailLabel = new javax.swing.JLabel();
        lblCourseLabel = new javax.swing.JLabel();
        lblCurrentGradeLabel = new javax.swing.JLabel();
        lblAssignmentsLabel = new javax.swing.JLabel();
        lblAttendanceLabel = new javax.swing.JLabel();
        lblNameValue = new javax.swing.JLabel();
        lblStudentIDValue = new javax.swing.JLabel();
        lblEmailValue = new javax.swing.JLabel();
        lblCourseValue = new javax.swing.JLabel();
        lblCurrentGradeValue = new javax.swing.JLabel();
        lblAssignmentsValue = new javax.swing.JLabel();
        lblAttendanceValue = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Student Progress Report");

        lblSelectStudents.setText("Select Students");

        cmbSelectStudents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectStudentsActionPerformed(evt);
            }
        });

        lblNameLabel.setText("Name:");

        lblStudentIDLabel.setText("Student ID:");

        lblEmailLabel.setText("Email:");

        lblCourseLabel.setText("Course:");

        lblCurrentGradeLabel.setText("Current Grade:");

        lblAssignmentsLabel.setText("Assignments");

        lblAttendanceLabel.setText("Attendance");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNameLabel)
                            .addComponent(lblSelectStudents)
                            .addComponent(lblStudentIDLabel)
                            .addComponent(lblEmailLabel)
                            .addComponent(lblCourseLabel)
                            .addComponent(lblCurrentGradeLabel)
                            .addComponent(lblAssignmentsLabel)
                            .addComponent(lblAttendanceLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmbSelectStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNameValue)
                                    .addComponent(lblStudentIDValue)
                                    .addComponent(lblEmailValue)
                                    .addComponent(lblCourseValue)
                                    .addComponent(lblCurrentGradeValue)
                                    .addComponent(lblAssignmentsValue)
                                    .addComponent(lblAttendanceValue))))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSelectStudents)
                            .addComponent(cmbSelectStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(lblNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblStudentIDLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmailLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblCourseLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrentGradeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblAssignmentsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblAttendanceLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNameValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblStudentIDValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmailValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblCourseValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrentGradeValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblAssignmentsValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblAttendanceValue)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSelectStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectStudentsActionPerformed
        // TODO add your handling code here:
        loadStudentProgress();
        
        
    }//GEN-LAST:event_cmbSelectStudentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSelectStudents;
    private javax.swing.JLabel lblAssignmentsLabel;
    private javax.swing.JLabel lblAssignmentsValue;
    private javax.swing.JLabel lblAttendanceLabel;
    private javax.swing.JLabel lblAttendanceValue;
    private javax.swing.JLabel lblCourseLabel;
    private javax.swing.JLabel lblCourseValue;
    private javax.swing.JLabel lblCurrentGradeLabel;
    private javax.swing.JLabel lblCurrentGradeValue;
    private javax.swing.JLabel lblEmailLabel;
    private javax.swing.JLabel lblEmailValue;
    private javax.swing.JLabel lblNameLabel;
    private javax.swing.JLabel lblNameValue;
    private javax.swing.JLabel lblSelectStudents;
    private javax.swing.JLabel lblStudentIDLabel;
    private javax.swing.JLabel lblStudentIDValue;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
