/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import Business.Business;
import Business.Profiles.StudentProfile;

/**
 *
 * @author emmanuelcroll
 */

public class StudentRankingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentRankingJPanel
     */
    
    Business business;
    javax.swing.JPanel CardSequencePanel;
    
    
      public StudentRankingJPanel(Business b, javax.swing.JPanel clp) {
        business = b;
        CardSequencePanel = clp;
        initComponents();
        populateCourseDropdown();
    }
      
      private void populateCourseDropdown() {
        cmbSelectStudents.removeAllItems();
        // ⚠️ HANK'S REVIEW: null check required here
        university.CourseSchedule.CourseSchedule cs =
            business.getDepartment().getCourseSchedule("Fall 2025");
        if (cs != null) {
            for (university.CourseSchedule.CourseOffer co : cs.getSchedule()) {
                cmbSelectStudents.addItem(co.getCourseNumber() + " - " +
                    co.getSubjectCourse().getName());
            }
        }
        cmbSelectStudents.addActionListener(e -> loadRankings());
        loadRankings();
    }
    
    private void loadRankings() {
        String[][] mockRankings = {
            {"1", "Alex Thompson", "95.5%", "A"},
            {"2", "Noah Lee", "91.8%", "A-"},
            {"3", "Emma Williams", "89.2%", "B+"},
            {"4", "Olivia Harris", "85.3%", "B"},
            {"5", "Liam Clark", "82.0%", "B"}
        };
        
        String[] columnNames = {"Rank", "Student Name", "Grade %", "Letter Grade"};
        
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(mockRankings, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tblStudentsRanking.setModel(model);
        
        lblClassGPAValue.setText("3.45 (B+)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbSelectStudents = new javax.swing.JComboBox<>();
        studentsRankingScrollPane = new javax.swing.JScrollPane();
        tblStudentsRanking = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblSelectCourse = new javax.swing.JLabel();
        lblClassGPA = new javax.swing.JLabel();
        lblClassGPAValue = new javax.swing.JLabel();

        cmbSelectStudents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectStudentsActionPerformed(evt);
            }
        });

        tblStudentsRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Rank", "Student Name", "Grade %", "Letter Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentsRankingScrollPane.setViewportView(tblStudentsRanking);

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Student Rankings");

        lblSelectCourse.setText("Select Course:");

        lblClassGPA.setText("Class GPA:");

        lblClassGPAValue.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblClassGPA)
                        .addGap(18, 18, 18)
                        .addComponent(lblClassGPAValue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(studentsRankingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(238, 238, 238)
                            .addComponent(lblTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(lblSelectCourse)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmbSelectStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(450, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassGPA)
                    .addComponent(lblClassGPAValue))
                .addGap(27, 27, 27)
                .addComponent(studentsRankingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(lblTitle)
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSelectCourse)
                        .addComponent(cmbSelectStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(490, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSelectStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectStudentsActionPerformed
        // TODO add your handling code here:
        loadRankings();
    }//GEN-LAST:event_cmbSelectStudentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSelectStudents;
    private javax.swing.JLabel lblClassGPA;
    private javax.swing.JLabel lblClassGPAValue;
    private javax.swing.JLabel lblSelectCourse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane studentsRankingScrollPane;
    private javax.swing.JTable tblStudentsRanking;
    // End of variables declaration//GEN-END:variables
}
