/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import Business.Business;
import Business.Profiles.StudentProfile;

/**
 *
 * @author emmanuelcroll
 */
public class StudentTranscriptViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentTranscriptViewJPanel
     */
    
    Business business;
    javax.swing.JPanel CardSequencePanel;
    
    public StudentTranscriptViewJPanel(Business b, javax.swing.JPanel clp) {
        business = b;
        CardSequencePanel = clp;
        initComponents();
        populateStudentDropdown();
    }
    
    private void populateStudentDropdown() {
        cmbSelectStudents.removeAllItems();
        for (StudentProfile sp :
                business.getStudentDirectory().getStudentList()) {
            cmbSelectStudents.addItem(sp.getPerson().getFullname() +
                " (" + sp.getPerson().getPersonId() + ")");
        }
        loadTranscript();
    }
    
    private void loadTranscript() {
        String selected = (String) cmbSelectStudents.getSelectedItem();
        if (selected == null) return;
        String id = selected.replaceAll(".*\\((.*)\\)", "$1").trim();
        StudentProfile bsp =
            business.getStudentDirectory().findStudentbyID(id);
        if (bsp == null || bsp.getUniversityProfile() == null) return;
        university.Persona.StudentProfile usp = bsp.getUniversityProfile();
        university.Persona.Transcript t = usp.getTranscript();

        java.util.ArrayList<university.CourseSchedule.SeatAssignment> courses =
            usp.getCourseList();
        String[][] data = new String[courses.size()][6];
        for (int i = 0; i < courses.size(); i++) {
            university.CourseSchedule.SeatAssignment sa = courses.get(i);
            String sem = "Fall 2025";
            data[i][0] = sem;
            data[i][1] = sa.getCourseOffer().getCourseNumber();
            data[i][2] = sa.getCourseOffer().getSubjectCourse().getName();
            data[i][3] = sa.getGrade();
            data[i][4] = String.format("%.2f", t.getSemesterGPA(sem));
            data[i][5] = String.format("%.2f", t.getOverallGPA());
        }
        String[] cols = {"Term", "Course ID", "Course Name", "Grade", "Term GPA", "Overall GPA"};
        javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel(data, cols) {
                @Override
                public boolean isCellEditable(int r, int c) { return false; }
            };
        tblTranscript.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSelectStudents = new javax.swing.JLabel();
        lblStudents = new javax.swing.JLabel();
        cmbSelectStudents = new javax.swing.JComboBox<>();
        lblStudentsValue = new javax.swing.JLabel();
        lblGPAValue = new javax.swing.JLabel();
        transcriptScrollPane = new javax.swing.JScrollPane();
        tblTranscript = new javax.swing.JTable();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("View Student Transcript");

        lblSelectStudents.setText("Select Students:");

        lblStudents.setText("Students:");

        cmbSelectStudents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectStudentsActionPerformed(evt);
            }
        });

        lblStudentsValue.setText("jLabel4");

        lblGPAValue.setText("jLabel5");

        tblTranscript.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Term", "Course ID", "Course Name", "Grade", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transcriptScrollPane.setViewportView(tblTranscript);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStudents)
                            .addComponent(lblSelectStudents))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSelectStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblStudentsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblGPAValue, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addComponent(transcriptScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectStudents)
                    .addComponent(cmbSelectStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudents)
                    .addComponent(lblStudentsValue)
                    .addComponent(lblGPAValue))
                .addGap(18, 18, 18)
                .addComponent(transcriptScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSelectStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectStudentsActionPerformed
        // TODO add your handling code here:
        loadTranscript();
    }//GEN-LAST:event_cmbSelectStudentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSelectStudents;
    private javax.swing.JLabel lblGPAValue;
    private javax.swing.JLabel lblSelectStudents;
    private javax.swing.JLabel lblStudents;
    private javax.swing.JLabel lblStudentsValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblTranscript;
    private javax.swing.JScrollPane transcriptScrollPane;
    // End of variables declaration//GEN-END:variables
}
