/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole; 

/**
 *
 * @author emmanuelcroll
 */
public class StudentProgressReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentProgressReportJPanel
     */
    public StudentProgressReportJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSelectStudents = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblNameLabel = new javax.swing.JLabel();
        lblStudentIDLabel = new javax.swing.JLabel();
        lblEmailLabel = new javax.swing.JLabel();
        lblCourseLabel = new javax.swing.JLabel();
        lblCurrentGradeLabel = new javax.swing.JLabel();
        lblAssignmentsLabel = new javax.swing.JLabel();
        lblAttendanceLabel = new javax.swing.JLabel();
        lblNameValue = new javax.swing.JLabel();
        lblStudentIDValue = new javax.swing.JLabel();
        lblEmailValue = new javax.swing.JLabel();
        lblCourseValue = new javax.swing.JLabel();
        lblCurrentGradeValue = new javax.swing.JLabel();
        lblAssignmentsValue = new javax.swing.JLabel();
        lblAttendanceValue = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Student Progress Report");

        lblSelectStudents.setText("Select Students");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNameLabel.setText("Name:");

        lblStudentIDLabel.setText("Student ID:");

        lblEmailLabel.setText("Email:");

        lblCourseLabel.setText("Course:");

        lblCurrentGradeLabel.setText("Current Grade:");

        lblAssignmentsLabel.setText("Assignments");

        lblAttendanceLabel.setText("Attendance");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNameLabel)
                            .addComponent(lblSelectStudents)
                            .addComponent(lblStudentIDLabel)
                            .addComponent(lblEmailLabel)
                            .addComponent(lblCourseLabel)
                            .addComponent(lblCurrentGradeLabel)
                            .addComponent(lblAssignmentsLabel)
                            .addComponent(lblAttendanceLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNameValue)
                                    .addComponent(lblStudentIDValue)
                                    .addComponent(lblEmailValue)
                                    .addComponent(lblCourseValue)
                                    .addComponent(lblCurrentGradeValue)
                                    .addComponent(lblAssignmentsValue)
                                    .addComponent(lblAttendanceValue))))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSelectStudents)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(lblNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblStudentIDLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmailLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblCourseLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrentGradeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblAssignmentsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblAttendanceLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNameValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblStudentIDValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmailValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblCourseValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrentGradeValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblAssignmentsValue)
                        .addGap(18, 18, 18)
                        .addComponent(lblAttendanceValue)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblAssignmentsLabel;
    private javax.swing.JLabel lblAssignmentsValue;
    private javax.swing.JLabel lblAttendanceLabel;
    private javax.swing.JLabel lblAttendanceValue;
    private javax.swing.JLabel lblCourseLabel;
    private javax.swing.JLabel lblCourseValue;
    private javax.swing.JLabel lblCurrentGradeLabel;
    private javax.swing.JLabel lblCurrentGradeValue;
    private javax.swing.JLabel lblEmailLabel;
    private javax.swing.JLabel lblEmailValue;
    private javax.swing.JLabel lblNameLabel;
    private javax.swing.JLabel lblNameValue;
    private javax.swing.JLabel lblSelectStudents;
    private javax.swing.JLabel lblStudentIDLabel;
    private javax.swing.JLabel lblStudentIDValue;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
