/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

/**
 *
 * @author emmanuelcroll
 */
public class StudentTranscriptViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentTranscriptViewJPanel
     */
    public StudentTranscriptViewJPanel() {
        initComponents();
        populateStudentDropdown();
    }
    
    private void populateStudentDropdown() {
        cmbSelectStudents.removeAllItems();
        cmbSelectStudents.addItem("Alex Thompson (S001)");
        cmbSelectStudents.addItem("Emma Williams (S002)");
        cmbSelectStudents.addItem("Noah Lee (S003)");
        
        cmbSelectStudents.addActionListener(e -> loadTranscript());
        loadTranscript();
    }
    
    private void loadTranscript() {
        String selected = (String) cmbSelectStudents.getSelectedItem();
        
        if (selected == null) return;
        
        String[][] transcriptData;
        String gpa;
        
        if (selected.contains("Alex")) {
            lblStudentsValue.setText("Alex Thompson (S001)");
            gpa = "3.85";
            transcriptData = new String[][] {
                {"Fall 2023", "INFO 5001", "Data Structures", "A", "4"},
                {"Fall 2023", "INFO 6205", "Program Structure", "A-", "4"},
                {"Spring 2024", "INFO 6150", "Web Design", "A", "4"},
                {"Spring 2024", "INFO 6250", "Web Development", "B+", "4"},
                {"Fall 2024", "INFO 5100", "Application Engineering", "A", "4"}
            };
        } else if (selected.contains("Emma")) {
            lblStudentsValue.setText("Emma Williams (S002)");
            gpa = "3.45";
            transcriptData = new String[][] {
                {"Fall 2023", "INFO 5001", "Data Structures", "B+", "4"},
                {"Fall 2023", "INFO 6205", "Program Structure", "B", "4"},
                {"Spring 2024", "INFO 6150", "Web Design", "A-", "4"},
                {"Fall 2024", "INFO 5100", "Application Engineering", "B+", "4"}
            };
        } else {
            lblStudentsValue.setText("Noah Lee (S003)");
            gpa = "3.67";
            transcriptData = new String[][] {
                {"Fall 2023", "INFO 5001", "Data Structures", "A", "4"},
                {"Spring 2024", "INFO 6205", "Program Structure", "A-", "4"},
                {"Spring 2024", "INFO 6250", "Web Development", "B+", "4"},
                {"Fall 2024", "INFO 5100", "Application Engineering", "A-", "4"}
            };
        }
        
        lblGPAValue.setText("GPA: " + gpa);
        
        String[] columnNames = {"Term", "Course ID", "Course Name", "Grade", "Credits"};
        
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(transcriptData, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tblTranscript.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSelectStudents = new javax.swing.JLabel();
        lblStudents = new javax.swing.JLabel();
        cmbSelectStudents = new javax.swing.JComboBox<>();
        lblStudentsValue = new javax.swing.JLabel();
        lblGPAValue = new javax.swing.JLabel();
        transcriptScrollPane = new javax.swing.JScrollPane();
        tblTranscript = new javax.swing.JTable();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("View Student Transcript");

        lblSelectStudents.setText("Select Students:");

        lblStudents.setText("Students:");

        cmbSelectStudents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectStudentsActionPerformed(evt);
            }
        });

        lblStudentsValue.setText("jLabel4");

        lblGPAValue.setText("jLabel5");

        tblTranscript.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Term", "Course ID", "Course Name", "Grade", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transcriptScrollPane.setViewportView(tblTranscript);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStudents)
                            .addComponent(lblSelectStudents))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSelectStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblStudentsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblGPAValue, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addComponent(transcriptScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectStudents)
                    .addComponent(cmbSelectStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudents)
                    .addComponent(lblStudentsValue)
                    .addComponent(lblGPAValue))
                .addGap(18, 18, 18)
                .addComponent(transcriptScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSelectStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectStudentsActionPerformed
        // TODO add your handling code here:
        loadTranscript();
    }//GEN-LAST:event_cmbSelectStudentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSelectStudents;
    private javax.swing.JLabel lblGPAValue;
    private javax.swing.JLabel lblSelectStudents;
    private javax.swing.JLabel lblStudents;
    private javax.swing.JLabel lblStudentsValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblTranscript;
    private javax.swing.JScrollPane transcriptScrollPane;
    // End of variables declaration//GEN-END:variables
}
