/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import Business.Business;
import Business.Profiles.StudentProfile;

/**
 *
 * @author emmanuelcroll
 */
public class TuitionInsightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TuitionInsightJPanel
     */
    Business business;
    javax.swing.JPanel CardSequencePanel;

    public TuitionInsightJPanel(Business b, javax.swing.JPanel clp) {
        business = b;
        CardSequencePanel = clp;
        initComponents();
        populateCourseDropdown();
    }
    
     private void populateCourseDropdown() {
        cmbSelectCourse.removeAllItems();
        // ⚠️ HANK'S REVIEW: null check required here
        university.CourseSchedule.CourseSchedule cs =
            business.getDepartment().getCourseSchedule("Fall 2025");
        if (cs != null) {
            for (university.CourseSchedule.CourseOffer co : cs.getSchedule()) {
                cmbSelectCourse.addItem(co.getCourseNumber() + " - " +
                    co.getSubjectCourse().getName());
            }
        }
        cmbSelectCourse.addActionListener(e -> loadTuitionData());
        loadTuitionData();
    }
    
    private void loadTuitionData() {
        String selected = (String) cmbSelectCourse.getSelectedItem();
        if (selected == null) return;
        String courseNum = selected.split(" - ")[0].trim();

        java.util.ArrayList<String[]> rows = new java.util.ArrayList<>();
        int enrolled = 0;
        int pricePerStudent = 0;

        for (StudentProfile bsp : business.getStudentDirectory().getStudentList()) {
            university.Persona.StudentProfile usp = bsp.getUniversityProfile();
            if (usp == null) continue;
            for (university.CourseSchedule.SeatAssignment sa : usp.getCourseList()) {
                if (sa.getCourseOffer().getCourseNumber().equals(courseNum)) {
                    pricePerStudent = sa.getAssociatedCourse().getCoursePrice();
                    String status = usp.isTuitionPaid() ? "Paid" : "Pending";
                    rows.add(new String[]{
                        bsp.getPerson().getFullname(),
                        String.valueOf(sa.getCreditHours()),
                        "$" + pricePerStudent,
                        status
                    });
                    enrolled++;
                }
            }
        }

        lblEnrollmentValue.setText(String.valueOf(enrolled));
        lblTuitionPerStudentValue.setText("$" + pricePerStudent);
        lblTotalRevenueValue.setText("$" + String.format("%,d", enrolled * pricePerStudent));

        String[][] data = rows.toArray(new String[0][]);
        String[] cols = {"Student Name", "Credits", "Tuition", "Status"};
        javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel(data, cols) {
                @Override
                public boolean isCellEditable(int r, int c) { return false; }
            };
        tblTuitionBreakdown.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnrollment = new javax.swing.JLabel();
        lblEnrollmentValue = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTotalRevenueValue = new javax.swing.JLabel();
        lblSelectCourse = new javax.swing.JLabel();
        tuitionScrollPane = new javax.swing.JScrollPane();
        tblTuitionBreakdown = new javax.swing.JTable();
        lblTuitionPerStudent = new javax.swing.JLabel();
        lblTotalRevenue = new javax.swing.JLabel();
        cmbSelectCourse = new javax.swing.JComboBox<>();
        lblTuitionPerStudentValue = new javax.swing.JLabel();

        lblEnrollment.setText("Enrolled Students:");

        lblEnrollmentValue.setText("jLabel8");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Tuition Revenue Insight");

        lblTotalRevenueValue.setText("jLabel10");

        lblSelectCourse.setText("Select Course:");

        tblTuitionBreakdown.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Name", "Credits", "Tuition", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tuitionScrollPane.setViewportView(tblTuitionBreakdown);

        lblTuitionPerStudent.setText("Tuition per Student:");

        lblTotalRevenue.setText("Total Revenue");

        cmbSelectCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectCourseActionPerformed(evt);
            }
        });

        lblTuitionPerStudentValue.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalRevenue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalRevenueValue))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnrollment)
                        .addGap(18, 18, 18)
                        .addComponent(lblEnrollmentValue)))
                .addContainerGap(430, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(203, 203, 203)
                            .addComponent(lblTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tuitionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTuitionPerStudent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblTuitionPerStudentValue))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSelectCourse)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnrollment)
                    .addComponent(lblEnrollmentValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalRevenue)
                    .addComponent(lblTotalRevenueValue))
                .addContainerGap(253, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(lblTitle)
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSelectCourse)
                        .addComponent(cmbSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTuitionPerStudent)
                        .addComponent(lblTuitionPerStudentValue))
                    .addGap(98, 98, 98)
                    .addComponent(tuitionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSelectCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectCourseActionPerformed
        // TODO add your handling code here:
                loadTuitionData();     
    }//GEN-LAST:event_cmbSelectCourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSelectCourse;
    private javax.swing.JLabel lblEnrollment;
    private javax.swing.JLabel lblEnrollmentValue;
    private javax.swing.JLabel lblSelectCourse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JLabel lblTotalRevenueValue;
    private javax.swing.JLabel lblTuitionPerStudent;
    private javax.swing.JLabel lblTuitionPerStudentValue;
    private javax.swing.JTable tblTuitionBreakdown;
    private javax.swing.JScrollPane tuitionScrollPane;
    // End of variables declaration//GEN-END:variables
}
