/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;
import Business.Business;
import Business.Profiles.StudentProfile;


/**
 *
 * @author emmanuelcroll
 */
public class ViewEnrolledStudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEnrolledStudentJPanel
     */
    
    Business business;
    javax.swing.JPanel CardSequencePanel;
    
    public ViewEnrolledStudentJPanel(Business b, javax.swing.JPanel clp) {
        business = b;
        CardSequencePanel = clp;
        initComponents();
        populateCourseDropdown();
    }
    
     private void populateCourseDropdown() {
    cmbSelectCourse.removeAllItems();
    university.CourseSchedule.CourseSchedule cs =
        business.getDepartment().getCourseSchedule("Fall 2025");
    if (cs != null) {
        for (university.CourseSchedule.CourseOffer co : cs.getSchedule()) {
            cmbSelectCourse.addItem(co.getCourseNumber() + " - " +
                co.getSubjectCourse().getName());
        }
    }
    cmbSelectCourse.addActionListener(e -> loadEnrolledStudents());
    loadEnrolledStudents();
}
    
    private void loadEnrolledStudents() {
        String selected = (String) cmbSelectCourse.getSelectedItem();
        if (selected == null) return;
        String courseNum = selected.split(" - ")[0].trim();

        // Get all students and check if enrolled in this course
        java.util.ArrayList<StudentProfile> allStudents =
            business.getStudentDirectory().getStudentList();

        java.util.ArrayList<String[]> rows = new java.util.ArrayList<>();
        for (StudentProfile bsp : allStudents) {
            university.Persona.StudentProfile usp = bsp.getUniversityProfile();
            if (usp == null) continue;
            for (university.CourseSchedule.SeatAssignment sa : usp.getCourseList()) {
                if (sa.getCourseOffer().getCourseNumber().equals(courseNum)) {
                    rows.add(new String[]{
                        bsp.getPerson().getPersonId(),
                        bsp.getPerson().getFullname(),
                        sa.getGrade()
                    });
                }
            }
        }

        String[][] data = rows.toArray(new String[0][]);
        String[] cols = {"Student ID", "Name", "Current Grade"};
        javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel(data, cols) {
                @Override
                public boolean isCellEditable(int row, int col) { return false; }
            };
        tblEnrolledStudents.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSelectCourse = new javax.swing.JLabel();
        cmbSelectCourse = new javax.swing.JComboBox<>();
        studentsScrollPane = new javax.swing.JScrollPane();
        tblEnrolledStudents = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("View Enrolled Students");

        lblSelectCourse.setText("Select Course:");

        cmbSelectCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblEnrolledStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Email", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentsScrollPane.setViewportView(tblEnrolledStudents);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblSelectCourse)
                .addGap(18, 18, 18)
                .addComponent(cmbSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(studentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addGap(367, 367, 367))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCourse)
                    .addComponent(cmbSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(studentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnRefresh)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadEnrolledStudents();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cmbSelectCourse;
    private javax.swing.JLabel lblSelectCourse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane studentsScrollPane;
    private javax.swing.JTable tblEnrolledStudents;
    // End of variables declaration//GEN-END:variables
}
