/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Business;
import university.Persona.Faculty.FacultyProfile;
import university.Persona.Faculty.FacultyAssignment;
import university.CourseSchedule.CourseOffer;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 * ViewAssignedCoursesJPanel.java
 * Faculty Panel 1 - View Assigned Courses
 * @author Emmanuel Ould Tayeb
 * INFO 5100 - Midterm Project
 */
    


public class ViewAssignedCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAssignedCoursesJPanel
     */
    
    Business business;
    javax.swing.JPanel CardSequencePanel;
    
    public ViewAssignedCoursesJPanel(Business b, javax.swing.JPanel clp) {
        business = b;
        CardSequencePanel = clp;
        initComponents();
        loadCourses();
    }
    
    private void loadCourses() {
        java.util.ArrayList<university.CourseSchedule.CourseOffer> offers =
            business.getDepartment().getCourseSchedule("Fall 2025").getSchedule();

        String[][] data = new String[offers.size()][5];
        for (int i = 0; i < offers.size(); i++) {
            university.CourseSchedule.CourseOffer co = offers.get(i);
            data[i][0] = co.getCourseNumber();
            data[i][1] = co.getSubjectCourse().getName();
            data[i][2] = "Fall 2025";
            data[i][3] = String.valueOf(co.getCapacity());
            data[i][4] = String.valueOf(co.getEnrolledCount());
        }

        String[] columnNames = {"Course ID", "Course Name", "Semester", "Capacity", "Enrolled"};
        javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel(data, columnNames) {
                @Override
                public boolean isCellEditable(int row, int column) { return false; }
            };
        tblViewAssignedCourses.setModel(model);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coursesScrollPane = new javax.swing.JScrollPane();
        tblViewAssignedCourses = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();

        tblViewAssignedCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Semester", "Capacity", "Enrolled"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        coursesScrollPane.setViewportView(tblViewAssignedCourses);

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("View Assigned Courses");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(coursesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(292, 292, 292))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(coursesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane coursesScrollPane;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblViewAssignedCourses;
    // End of variables declaration//GEN-END:variables
}
